/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.0.9-SNAPSHOT
 */
import type {
  ForwardReference,
  OutboundSseEvent,
  ResourcePayload,
  ResourceReference,
  ServiceState,
  ServiceTarget,
  ToolPayload,
  ToolReference,
  WanakuResponse,
  WanakuResponseListForwardReference,
  WanakuResponseListNamespace,
  WanakuResponseListResourceReference,
  WanakuResponseListServiceTarget,
  WanakuResponseListToolReference,
  WanakuResponseMapStringListActivityRecord,
  WanakuResponseResourceReference,
  WanakuResponseServerInfo,
  WanakuResponseServiceTarget,
  WanakuResponseToolReference,
} from "../models";

import { customFetch } from "../custom-fetch";
/**
 * @summary Targets Event Stream
 */
export type getApiV1CapabilitiesNotificationsResponse200 = {
  data: OutboundSseEvent[];
  status: 200;
};

export type getApiV1CapabilitiesNotificationsResponseComposite =
  getApiV1CapabilitiesNotificationsResponse200;

export type getApiV1CapabilitiesNotificationsResponse =
  getApiV1CapabilitiesNotificationsResponseComposite & {
    headers: Headers;
  };

export const getGetApiV1CapabilitiesNotificationsUrl = () => {
  return `/api/v1/capabilities/notifications`;
};

export const getApiV1CapabilitiesNotifications = async (
  options?: RequestInit,
): Promise<getApiV1CapabilitiesNotificationsResponse> => {
  return customFetch<getApiV1CapabilitiesNotificationsResponse>(
    getGetApiV1CapabilitiesNotificationsUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Resources List
 */
export type getApiV1CapabilitiesResourcesListResponse200 = {
  data: WanakuResponseListServiceTarget;
  status: 200;
};

export type getApiV1CapabilitiesResourcesListResponseComposite =
  getApiV1CapabilitiesResourcesListResponse200;

export type getApiV1CapabilitiesResourcesListResponse =
  getApiV1CapabilitiesResourcesListResponseComposite & {
    headers: Headers;
  };

export const getGetApiV1CapabilitiesResourcesListUrl = () => {
  return `/api/v1/capabilities/resources/list`;
};

export const getApiV1CapabilitiesResourcesList = async (
  options?: RequestInit,
): Promise<getApiV1CapabilitiesResourcesListResponse> => {
  return customFetch<getApiV1CapabilitiesResourcesListResponse>(
    getGetApiV1CapabilitiesResourcesListUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Resources State
 */
export type getApiV1CapabilitiesResourcesStateResponse200 = {
  data: WanakuResponseMapStringListActivityRecord;
  status: 200;
};

export type getApiV1CapabilitiesResourcesStateResponseComposite =
  getApiV1CapabilitiesResourcesStateResponse200;

export type getApiV1CapabilitiesResourcesStateResponse =
  getApiV1CapabilitiesResourcesStateResponseComposite & {
    headers: Headers;
  };

export const getGetApiV1CapabilitiesResourcesStateUrl = () => {
  return `/api/v1/capabilities/resources/state`;
};

export const getApiV1CapabilitiesResourcesState = async (
  options?: RequestInit,
): Promise<getApiV1CapabilitiesResourcesStateResponse> => {
  return customFetch<getApiV1CapabilitiesResourcesStateResponse>(
    getGetApiV1CapabilitiesResourcesStateUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Tool List
 */
export type getApiV1CapabilitiesToolsListResponse200 = {
  data: WanakuResponseListServiceTarget;
  status: 200;
};

export type getApiV1CapabilitiesToolsListResponseComposite =
  getApiV1CapabilitiesToolsListResponse200;

export type getApiV1CapabilitiesToolsListResponse =
  getApiV1CapabilitiesToolsListResponseComposite & {
    headers: Headers;
  };

export const getGetApiV1CapabilitiesToolsListUrl = () => {
  return `/api/v1/capabilities/tools/list`;
};

export const getApiV1CapabilitiesToolsList = async (
  options?: RequestInit,
): Promise<getApiV1CapabilitiesToolsListResponse> => {
  return customFetch<getApiV1CapabilitiesToolsListResponse>(
    getGetApiV1CapabilitiesToolsListUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Tools State
 */
export type getApiV1CapabilitiesToolsStateResponse200 = {
  data: WanakuResponseMapStringListActivityRecord;
  status: 200;
};

export type getApiV1CapabilitiesToolsStateResponseComposite =
  getApiV1CapabilitiesToolsStateResponse200;

export type getApiV1CapabilitiesToolsStateResponse =
  getApiV1CapabilitiesToolsStateResponseComposite & {
    headers: Headers;
  };

export const getGetApiV1CapabilitiesToolsStateUrl = () => {
  return `/api/v1/capabilities/tools/state`;
};

export const getApiV1CapabilitiesToolsState = async (
  options?: RequestInit,
): Promise<getApiV1CapabilitiesToolsStateResponse> => {
  return customFetch<getApiV1CapabilitiesToolsStateResponse>(
    getGetApiV1CapabilitiesToolsStateUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary List Forwards
 */
export type getApiV1ForwardsResponse200 = {
  data: WanakuResponseListForwardReference;
  status: 200;
};

export type getApiV1ForwardsResponseComposite = getApiV1ForwardsResponse200;

export type getApiV1ForwardsResponse = getApiV1ForwardsResponseComposite & {
  headers: Headers;
};

export const getGetApiV1ForwardsUrl = () => {
  return `/api/v1/forwards`;
};

export const getApiV1Forwards = async (
  options?: RequestInit,
): Promise<getApiV1ForwardsResponse> => {
  return customFetch<getApiV1ForwardsResponse>(getGetApiV1ForwardsUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Add Forward
 */
export type postApiV1ForwardsResponse200 = {
  data: null;
  status: 200;
};

export type postApiV1ForwardsResponse400 = {
  data: null;
  status: 400;
};

export type postApiV1ForwardsResponseComposite =
  | postApiV1ForwardsResponse200
  | postApiV1ForwardsResponse400;

export type postApiV1ForwardsResponse = postApiV1ForwardsResponseComposite & {
  headers: Headers;
};

export const getPostApiV1ForwardsUrl = () => {
  return `/api/v1/forwards`;
};

export const postApiV1Forwards = async (
  forwardReference: ForwardReference,
  options?: RequestInit,
): Promise<postApiV1ForwardsResponse> => {
  return customFetch<postApiV1ForwardsResponse>(getPostApiV1ForwardsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(forwardReference),
  });
};

/**
 * @summary Update
 */
export type putApiV1ForwardsForwardNameResponse200 = {
  data: null;
  status: 200;
};

export type putApiV1ForwardsForwardNameResponse400 = {
  data: null;
  status: 400;
};

export type putApiV1ForwardsForwardNameResponseComposite =
  | putApiV1ForwardsForwardNameResponse200
  | putApiV1ForwardsForwardNameResponse400;

export type putApiV1ForwardsForwardNameResponse =
  putApiV1ForwardsForwardNameResponseComposite & {
    headers: Headers;
  };

export const getPutApiV1ForwardsForwardNameUrl = (forwardName: string) => {
  return `/api/v1/forwards/${forwardName}`;
};

export const putApiV1ForwardsForwardName = async (
  forwardName: string,
  forwardReference: ForwardReference,
  options?: RequestInit,
): Promise<putApiV1ForwardsForwardNameResponse> => {
  return customFetch<putApiV1ForwardsForwardNameResponse>(
    getPutApiV1ForwardsForwardNameUrl(forwardName),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(forwardReference),
    },
  );
};

/**
 * @summary Remove Forward
 */
export type deleteApiV1ForwardsForwardNameResponse200 = {
  data: null;
  status: 200;
};

export type deleteApiV1ForwardsForwardNameResponseComposite =
  deleteApiV1ForwardsForwardNameResponse200;

export type deleteApiV1ForwardsForwardNameResponse =
  deleteApiV1ForwardsForwardNameResponseComposite & {
    headers: Headers;
  };

export const getDeleteApiV1ForwardsForwardNameUrl = (forwardName: string) => {
  return `/api/v1/forwards/${forwardName}`;
};

export const deleteApiV1ForwardsForwardName = async (
  forwardName: string,
  options?: RequestInit,
): Promise<deleteApiV1ForwardsForwardNameResponse> => {
  return customFetch<deleteApiV1ForwardsForwardNameResponse>(
    getDeleteApiV1ForwardsForwardNameUrl(forwardName),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Deregister
 */
export type postApiV1ManagementDiscoveryDeregisterResponse200 = {
  data: null;
  status: 200;
};

export type postApiV1ManagementDiscoveryDeregisterResponse400 = {
  data: null;
  status: 400;
};

export type postApiV1ManagementDiscoveryDeregisterResponseComposite =
  | postApiV1ManagementDiscoveryDeregisterResponse200
  | postApiV1ManagementDiscoveryDeregisterResponse400;

export type postApiV1ManagementDiscoveryDeregisterResponse =
  postApiV1ManagementDiscoveryDeregisterResponseComposite & {
    headers: Headers;
  };

export const getPostApiV1ManagementDiscoveryDeregisterUrl = () => {
  return `/api/v1/management/discovery/deregister`;
};

export const postApiV1ManagementDiscoveryDeregister = async (
  serviceTarget: ServiceTarget,
  options?: RequestInit,
): Promise<postApiV1ManagementDiscoveryDeregisterResponse> => {
  return customFetch<postApiV1ManagementDiscoveryDeregisterResponse>(
    getPostApiV1ManagementDiscoveryDeregisterUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(serviceTarget),
    },
  );
};

/**
 * @summary Ping
 */
export type postApiV1ManagementDiscoveryPingResponse200 = {
  data: null;
  status: 200;
};

export type postApiV1ManagementDiscoveryPingResponseComposite =
  postApiV1ManagementDiscoveryPingResponse200;

export type postApiV1ManagementDiscoveryPingResponse =
  postApiV1ManagementDiscoveryPingResponseComposite & {
    headers: Headers;
  };

export const getPostApiV1ManagementDiscoveryPingUrl = () => {
  return `/api/v1/management/discovery/ping`;
};

export const postApiV1ManagementDiscoveryPing = async (
  postApiV1ManagementDiscoveryPingBody: string,
  options?: RequestInit,
): Promise<postApiV1ManagementDiscoveryPingResponse> => {
  return customFetch<postApiV1ManagementDiscoveryPingResponse>(
    getPostApiV1ManagementDiscoveryPingUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(postApiV1ManagementDiscoveryPingBody),
    },
  );
};

/**
 * @summary Register
 */
export type postApiV1ManagementDiscoveryRegisterResponse200 = {
  data: WanakuResponseServiceTarget;
  status: 200;
};

export type postApiV1ManagementDiscoveryRegisterResponse400 = {
  data: null;
  status: 400;
};

export type postApiV1ManagementDiscoveryRegisterResponseComposite =
  | postApiV1ManagementDiscoveryRegisterResponse200
  | postApiV1ManagementDiscoveryRegisterResponse400;

export type postApiV1ManagementDiscoveryRegisterResponse =
  postApiV1ManagementDiscoveryRegisterResponseComposite & {
    headers: Headers;
  };

export const getPostApiV1ManagementDiscoveryRegisterUrl = () => {
  return `/api/v1/management/discovery/register`;
};

export const postApiV1ManagementDiscoveryRegister = async (
  serviceTarget: ServiceTarget,
  options?: RequestInit,
): Promise<postApiV1ManagementDiscoveryRegisterResponse> => {
  return customFetch<postApiV1ManagementDiscoveryRegisterResponse>(
    getPostApiV1ManagementDiscoveryRegisterUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(serviceTarget),
    },
  );
};

/**
 * @summary Update State
 */
export type postApiV1ManagementDiscoveryUpdateIdResponse200 = {
  data: null;
  status: 200;
};

export type postApiV1ManagementDiscoveryUpdateIdResponse400 = {
  data: null;
  status: 400;
};

export type postApiV1ManagementDiscoveryUpdateIdResponseComposite =
  | postApiV1ManagementDiscoveryUpdateIdResponse200
  | postApiV1ManagementDiscoveryUpdateIdResponse400;

export type postApiV1ManagementDiscoveryUpdateIdResponse =
  postApiV1ManagementDiscoveryUpdateIdResponseComposite & {
    headers: Headers;
  };

export const getPostApiV1ManagementDiscoveryUpdateIdUrl = (id: string) => {
  return `/api/v1/management/discovery/update/${id}`;
};

export const postApiV1ManagementDiscoveryUpdateId = async (
  id: string,
  serviceState: ServiceState,
  options?: RequestInit,
): Promise<postApiV1ManagementDiscoveryUpdateIdResponse> => {
  return customFetch<postApiV1ManagementDiscoveryUpdateIdResponse>(
    getPostApiV1ManagementDiscoveryUpdateIdUrl(id),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(serviceState),
    },
  );
};

/**
 * @summary Version
 */
export type getApiV1ManagementInfoVersionResponse200 = {
  data: WanakuResponseServerInfo;
  status: 200;
};

export type getApiV1ManagementInfoVersionResponseComposite =
  getApiV1ManagementInfoVersionResponse200;

export type getApiV1ManagementInfoVersionResponse =
  getApiV1ManagementInfoVersionResponseComposite & {
    headers: Headers;
  };

export const getGetApiV1ManagementInfoVersionUrl = () => {
  return `/api/v1/management/info/version`;
};

export const getApiV1ManagementInfoVersion = async (
  options?: RequestInit,
): Promise<getApiV1ManagementInfoVersionResponse> => {
  return customFetch<getApiV1ManagementInfoVersionResponse>(
    getGetApiV1ManagementInfoVersionUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary List
 */
export type getApiV1NamespacesListResponse200 = {
  data: WanakuResponseListNamespace;
  status: 200;
};

export type getApiV1NamespacesListResponseComposite =
  getApiV1NamespacesListResponse200;

export type getApiV1NamespacesListResponse =
  getApiV1NamespacesListResponseComposite & {
    headers: Headers;
  };

export const getGetApiV1NamespacesListUrl = () => {
  return `/api/v1/namespaces/list`;
};

export const getApiV1NamespacesList = async (
  options?: RequestInit,
): Promise<getApiV1NamespacesListResponse> => {
  return customFetch<getApiV1NamespacesListResponse>(
    getGetApiV1NamespacesListUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary List
 */
export type getApiV1ResourcesResponse200 = {
  data: WanakuResponseListResourceReference;
  status: 200;
};

export type getApiV1ResourcesResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type getApiV1ResourcesResponseComposite =
  | getApiV1ResourcesResponse200
  | getApiV1ResourcesResponse500;

export type getApiV1ResourcesResponse = getApiV1ResourcesResponseComposite & {
  headers: Headers;
};

export const getGetApiV1ResourcesUrl = () => {
  return `/api/v1/resources`;
};

export const getApiV1Resources = async (
  options?: RequestInit,
): Promise<getApiV1ResourcesResponse> => {
  return customFetch<getApiV1ResourcesResponse>(getGetApiV1ResourcesUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Expose
 */
export type postApiV1ResourcesResponse200 = {
  data: WanakuResponseResourceReference;
  status: 200;
};

export type postApiV1ResourcesResponse400 = {
  data: null;
  status: 400;
};

export type postApiV1ResourcesResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type postApiV1ResourcesResponseComposite =
  | postApiV1ResourcesResponse200
  | postApiV1ResourcesResponse400
  | postApiV1ResourcesResponse500;

export type postApiV1ResourcesResponse = postApiV1ResourcesResponseComposite & {
  headers: Headers;
};

export const getPostApiV1ResourcesUrl = () => {
  return `/api/v1/resources`;
};

export const postApiV1Resources = async (
  resourceReference: ResourceReference,
  options?: RequestInit,
): Promise<postApiV1ResourcesResponse> => {
  return customFetch<postApiV1ResourcesResponse>(getPostApiV1ResourcesUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(resourceReference),
  });
};

/**
 * @summary Expose With Payload
 */
export type postApiV1ResourcesWithPayloadResponse200 = {
  data: WanakuResponseResourceReference;
  status: 200;
};

export type postApiV1ResourcesWithPayloadResponse400 = {
  data: null;
  status: 400;
};

export type postApiV1ResourcesWithPayloadResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type postApiV1ResourcesWithPayloadResponseComposite =
  | postApiV1ResourcesWithPayloadResponse200
  | postApiV1ResourcesWithPayloadResponse400
  | postApiV1ResourcesWithPayloadResponse500;

export type postApiV1ResourcesWithPayloadResponse =
  postApiV1ResourcesWithPayloadResponseComposite & {
    headers: Headers;
  };

export const getPostApiV1ResourcesWithPayloadUrl = () => {
  return `/api/v1/resources/with-payload`;
};

export const postApiV1ResourcesWithPayload = async (
  resourcePayload: ResourcePayload,
  options?: RequestInit,
): Promise<postApiV1ResourcesWithPayloadResponse> => {
  return customFetch<postApiV1ResourcesWithPayloadResponse>(
    getPostApiV1ResourcesWithPayloadUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(resourcePayload),
    },
  );
};

/**
 * @summary Update
 */
export type putApiV1ResourcesResourceNameResponse200 = {
  data: null;
  status: 200;
};

export type putApiV1ResourcesResourceNameResponse400 = {
  data: null;
  status: 400;
};

export type putApiV1ResourcesResourceNameResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type putApiV1ResourcesResourceNameResponseComposite =
  | putApiV1ResourcesResourceNameResponse200
  | putApiV1ResourcesResourceNameResponse400
  | putApiV1ResourcesResourceNameResponse500;

export type putApiV1ResourcesResourceNameResponse =
  putApiV1ResourcesResourceNameResponseComposite & {
    headers: Headers;
  };

export const getPutApiV1ResourcesResourceNameUrl = (resourceName: string) => {
  return `/api/v1/resources/${resourceName}`;
};

export const putApiV1ResourcesResourceName = async (
  resourceName: string,
  resourceReference: ResourceReference,
  options?: RequestInit,
): Promise<putApiV1ResourcesResourceNameResponse> => {
  return customFetch<putApiV1ResourcesResourceNameResponse>(
    getPutApiV1ResourcesResourceNameUrl(resourceName),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(resourceReference),
    },
  );
};

/**
 * @summary Remove
 */
export type deleteApiV1ResourcesResourceNameResponse200 = {
  data: null;
  status: 200;
};

export type deleteApiV1ResourcesResourceNameResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type deleteApiV1ResourcesResourceNameResponseComposite =
  | deleteApiV1ResourcesResourceNameResponse200
  | deleteApiV1ResourcesResourceNameResponse500;

export type deleteApiV1ResourcesResourceNameResponse =
  deleteApiV1ResourcesResourceNameResponseComposite & {
    headers: Headers;
  };

export const getDeleteApiV1ResourcesResourceNameUrl = (
  resourceName: string,
) => {
  return `/api/v1/resources/${resourceName}`;
};

export const deleteApiV1ResourcesResourceName = async (
  resourceName: string,
  options?: RequestInit,
): Promise<deleteApiV1ResourcesResourceNameResponse> => {
  return customFetch<deleteApiV1ResourcesResourceNameResponse>(
    getDeleteApiV1ResourcesResourceNameUrl(resourceName),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary List
 */
export type getApiV1ToolsResponse200 = {
  data: WanakuResponseListToolReference;
  status: 200;
};

export type getApiV1ToolsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type getApiV1ToolsResponseComposite =
  | getApiV1ToolsResponse200
  | getApiV1ToolsResponse500;

export type getApiV1ToolsResponse = getApiV1ToolsResponseComposite & {
  headers: Headers;
};

export const getGetApiV1ToolsUrl = () => {
  return `/api/v1/tools`;
};

export const getApiV1Tools = async (
  options?: RequestInit,
): Promise<getApiV1ToolsResponse> => {
  return customFetch<getApiV1ToolsResponse>(getGetApiV1ToolsUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Add
 */
export type postApiV1ToolsResponse200 = {
  data: WanakuResponseToolReference;
  status: 200;
};

export type postApiV1ToolsResponse400 = {
  data: null;
  status: 400;
};

export type postApiV1ToolsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type postApiV1ToolsResponseComposite =
  | postApiV1ToolsResponse200
  | postApiV1ToolsResponse400
  | postApiV1ToolsResponse500;

export type postApiV1ToolsResponse = postApiV1ToolsResponseComposite & {
  headers: Headers;
};

export const getPostApiV1ToolsUrl = () => {
  return `/api/v1/tools`;
};

export const postApiV1Tools = async (
  toolReference: ToolReference,
  options?: RequestInit,
): Promise<postApiV1ToolsResponse> => {
  return customFetch<postApiV1ToolsResponse>(getPostApiV1ToolsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(toolReference),
  });
};

/**
 * @summary Add With Payload
 */
export type postApiV1ToolsWithPayloadResponse200 = {
  data: WanakuResponseToolReference;
  status: 200;
};

export type postApiV1ToolsWithPayloadResponse400 = {
  data: null;
  status: 400;
};

export type postApiV1ToolsWithPayloadResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type postApiV1ToolsWithPayloadResponseComposite =
  | postApiV1ToolsWithPayloadResponse200
  | postApiV1ToolsWithPayloadResponse400
  | postApiV1ToolsWithPayloadResponse500;

export type postApiV1ToolsWithPayloadResponse =
  postApiV1ToolsWithPayloadResponseComposite & {
    headers: Headers;
  };

export const getPostApiV1ToolsWithPayloadUrl = () => {
  return `/api/v1/tools/with-payload`;
};

export const postApiV1ToolsWithPayload = async (
  toolPayload: ToolPayload,
  options?: RequestInit,
): Promise<postApiV1ToolsWithPayloadResponse> => {
  return customFetch<postApiV1ToolsWithPayloadResponse>(
    getPostApiV1ToolsWithPayloadUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(toolPayload),
    },
  );
};

/**
 * @summary Update
 */
export type putApiV1ToolsToolNameResponse200 = {
  data: null;
  status: 200;
};

export type putApiV1ToolsToolNameResponse400 = {
  data: null;
  status: 400;
};

export type putApiV1ToolsToolNameResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type putApiV1ToolsToolNameResponseComposite =
  | putApiV1ToolsToolNameResponse200
  | putApiV1ToolsToolNameResponse400
  | putApiV1ToolsToolNameResponse500;

export type putApiV1ToolsToolNameResponse =
  putApiV1ToolsToolNameResponseComposite & {
    headers: Headers;
  };

export const getPutApiV1ToolsToolNameUrl = (toolName: string) => {
  return `/api/v1/tools/${toolName}`;
};

export const putApiV1ToolsToolName = async (
  toolName: string,
  toolReference: ToolReference,
  options?: RequestInit,
): Promise<putApiV1ToolsToolNameResponse> => {
  return customFetch<putApiV1ToolsToolNameResponse>(
    getPutApiV1ToolsToolNameUrl(toolName),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(toolReference),
    },
  );
};

/**
 * @summary Remove
 */
export type deleteApiV1ToolsToolNameResponse200 = {
  data: null;
  status: 200;
};

export type deleteApiV1ToolsToolNameResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type deleteApiV1ToolsToolNameResponseComposite =
  | deleteApiV1ToolsToolNameResponse200
  | deleteApiV1ToolsToolNameResponse500;

export type deleteApiV1ToolsToolNameResponse =
  deleteApiV1ToolsToolNameResponseComposite & {
    headers: Headers;
  };

export const getDeleteApiV1ToolsToolNameUrl = (toolName: string) => {
  return `/api/v1/tools/${toolName}`;
};

export const deleteApiV1ToolsToolName = async (
  toolName: string,
  options?: RequestInit,
): Promise<deleteApiV1ToolsToolNameResponse> => {
  return customFetch<deleteApiV1ToolsToolNameResponse>(
    getDeleteApiV1ToolsToolNameUrl(toolName),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Get By Name
 */
export type getApiV1ToolsToolNameResponse200 = {
  data: WanakuResponseToolReference;
  status: 200;
};

export type getApiV1ToolsToolNameResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type getApiV1ToolsToolNameResponseComposite =
  | getApiV1ToolsToolNameResponse200
  | getApiV1ToolsToolNameResponse500;

export type getApiV1ToolsToolNameResponse =
  getApiV1ToolsToolNameResponseComposite & {
    headers: Headers;
  };

export const getGetApiV1ToolsToolNameUrl = (toolName: string) => {
  return `/api/v1/tools/${toolName}`;
};

export const getApiV1ToolsToolName = async (
  toolName: string,
  options?: RequestInit,
): Promise<getApiV1ToolsToolNameResponse> => {
  return customFetch<getApiV1ToolsToolNameResponse>(
    getGetApiV1ToolsToolNameUrl(toolName),
    {
      ...options,
      method: "GET",
    },
  );
};
