/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */
import type {
  CodeExecutionError,
  CodeExecutionRequest,
  CodeExecutionResponse,
  DataStore,
  DeleteApiV1CapabilitiesStaleParams,
  DeleteApiV1DataStoreLabelsParams,
  DeleteApiV1DataStoreParams,
  DeleteApiV1PromptsParams,
  DeleteApiV1ToolsParams,
  ForwardReference,
  GetApiV1CapabilitiesStaleParams,
  GetApiV1DataStoreParams,
  GetApiV1ForwardsParams,
  GetApiV1NamespacesParams,
  GetApiV1ResourcesParams,
  GetApiV1ToolsParams,
  Namespace,
  OutboundSseEvent,
  PromptPayload,
  PromptReference,
  ResourcePayload,
  ResourceReference,
  ServiceTarget,
  ToolPayload,
  ToolReference,
  WanakuResponse,
  WanakuResponseDataStore,
  WanakuResponseFleetStatus,
  WanakuResponseForwardReference,
  WanakuResponseInteger,
  WanakuResponseListDataStore,
  WanakuResponseListForwardReference,
  WanakuResponseListNamespace,
  WanakuResponseListPromptReference,
  WanakuResponseListResourceReference,
  WanakuResponseListServiceTarget,
  WanakuResponseListStaleCapabilityInfo,
  WanakuResponseListToolReference,
  WanakuResponseMapStringListActivityRecord,
  WanakuResponseNamespace,
  WanakuResponsePromptReference,
  WanakuResponseResourceReference,
  WanakuResponseServerInfo,
  WanakuResponseServiceTarget,
  WanakuResponseSystemStatistics,
  WanakuResponseToolReference,
} from "../models";

import { customFetch } from "../custom-fetch";
/**
 * @summary Get Authorization Server Metadata
 */
export type getWellKnownOauthAuthorizationServerResponse200 = {
  data: null;
  status: 200;
};

export type getWellKnownOauthAuthorizationServerResponseComposite =
  getWellKnownOauthAuthorizationServerResponse200;

export type getWellKnownOauthAuthorizationServerResponse =
  getWellKnownOauthAuthorizationServerResponseComposite & {
    headers: Headers;
  };

export const getGetWellKnownOauthAuthorizationServerUrl = () => {
  return `/.well-known/oauth-authorization-server`;
};

export const getWellKnownOauthAuthorizationServer = async (
  options?: RequestInit,
): Promise<getWellKnownOauthAuthorizationServerResponse> => {
  return customFetch<getWellKnownOauthAuthorizationServerResponse>(
    getGetWellKnownOauthAuthorizationServerUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get Authorization Server Metadata For Tenant
 */
export type getWellKnownOauthAuthorizationServerTenantResponse200 = {
  data: null;
  status: 200;
};

export type getWellKnownOauthAuthorizationServerTenantResponseComposite =
  getWellKnownOauthAuthorizationServerTenantResponse200;

export type getWellKnownOauthAuthorizationServerTenantResponse =
  getWellKnownOauthAuthorizationServerTenantResponseComposite & {
    headers: Headers;
  };

export const getGetWellKnownOauthAuthorizationServerTenantUrl = (
  tenant: string,
) => {
  return `/.well-known/oauth-authorization-server/${tenant}`;
};

export const getWellKnownOauthAuthorizationServerTenant = async (
  tenant: string,
  options?: RequestInit,
): Promise<getWellKnownOauthAuthorizationServerTenantResponse> => {
  return customFetch<getWellKnownOauthAuthorizationServerTenantResponse>(
    getGetWellKnownOauthAuthorizationServerTenantUrl(tenant),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary List
 */
export type getApiV1CapabilitiesResponse200 = {
  data: WanakuResponseListServiceTarget;
  status: 200;
};

export type getApiV1CapabilitiesResponseSuccess =
  getApiV1CapabilitiesResponse200 & {
    headers: Headers;
  };
export type getApiV1CapabilitiesResponse = getApiV1CapabilitiesResponseSuccess;

export const getGetApiV1CapabilitiesUrl = () => {
  return `/api/v1/capabilities`;
};

export const getApiV1Capabilities = async (
  options?: RequestInit,
): Promise<getApiV1CapabilitiesResponse> => {
  return customFetch<getApiV1CapabilitiesResponse>(
    getGetApiV1CapabilitiesUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Fleet Status
 */
export type getApiV1CapabilitiesFleetStatusResponse200 = {
  data: WanakuResponseFleetStatus;
  status: 200;
};

export type getApiV1CapabilitiesFleetStatusResponseSuccess =
  getApiV1CapabilitiesFleetStatusResponse200 & {
    headers: Headers;
  };
export type getApiV1CapabilitiesFleetStatusResponse =
  getApiV1CapabilitiesFleetStatusResponseSuccess;

export const getGetApiV1CapabilitiesFleetStatusUrl = () => {
  return `/api/v1/capabilities/fleet/status`;
};

export const getApiV1CapabilitiesFleetStatus = async (
  options?: RequestInit,
): Promise<getApiV1CapabilitiesFleetStatusResponse> => {
  return customFetch<getApiV1CapabilitiesFleetStatusResponse>(
    getGetApiV1CapabilitiesFleetStatusUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Targets Event Stream
 */
export type getApiV1CapabilitiesNotificationsResponse200 = {
  data: OutboundSseEvent[];
  status: 200;
};

export type getApiV1CapabilitiesNotificationsResponseSuccess =
  getApiV1CapabilitiesNotificationsResponse200 & {
    headers: Headers;
  };
export type getApiV1CapabilitiesNotificationsResponse =
  getApiV1CapabilitiesNotificationsResponseSuccess;

export const getGetApiV1CapabilitiesNotificationsUrl = () => {
  return `/api/v1/capabilities/notifications`;
};

export const getApiV1CapabilitiesNotifications = async (
  options?: RequestInit,
): Promise<getApiV1CapabilitiesNotificationsResponse> => {
  return customFetch<getApiV1CapabilitiesNotificationsResponse>(
    getGetApiV1CapabilitiesNotificationsUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Resources State
 */
export type getApiV1CapabilitiesResourcesStateResponse200 = {
  data: WanakuResponseMapStringListActivityRecord;
  status: 200;
};

export type getApiV1CapabilitiesResourcesStateResponseSuccess =
  getApiV1CapabilitiesResourcesStateResponse200 & {
    headers: Headers;
  };
export type getApiV1CapabilitiesResourcesStateResponse =
  getApiV1CapabilitiesResourcesStateResponseSuccess;

export const getGetApiV1CapabilitiesResourcesStateUrl = () => {
  return `/api/v1/capabilities/resources/state`;
};

export const getApiV1CapabilitiesResourcesState = async (
  options?: RequestInit,
): Promise<getApiV1CapabilitiesResourcesStateResponse> => {
  return customFetch<getApiV1CapabilitiesResourcesStateResponse>(
    getGetApiV1CapabilitiesResourcesStateUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary List Stale
 */
export type getApiV1CapabilitiesStaleResponse200 = {
  data: WanakuResponseListStaleCapabilityInfo;
  status: 200;
};

export type getApiV1CapabilitiesStaleResponseSuccess =
  getApiV1CapabilitiesStaleResponse200 & {
    headers: Headers;
  };
export type getApiV1CapabilitiesStaleResponse =
  getApiV1CapabilitiesStaleResponseSuccess;

export const getGetApiV1CapabilitiesStaleUrl = (
  params?: GetApiV1CapabilitiesStaleParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/capabilities/stale?${stringifiedParams}`
    : `/api/v1/capabilities/stale`;
};

export const getApiV1CapabilitiesStale = async (
  params?: GetApiV1CapabilitiesStaleParams,
  options?: RequestInit,
): Promise<getApiV1CapabilitiesStaleResponse> => {
  return customFetch<getApiV1CapabilitiesStaleResponse>(
    getGetApiV1CapabilitiesStaleUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Cleanup Stale
 */
export type deleteApiV1CapabilitiesStaleResponse200 = {
  data: WanakuResponseInteger;
  status: 200;
};

export type deleteApiV1CapabilitiesStaleResponseSuccess =
  deleteApiV1CapabilitiesStaleResponse200 & {
    headers: Headers;
  };
export type deleteApiV1CapabilitiesStaleResponse =
  deleteApiV1CapabilitiesStaleResponseSuccess;

export const getDeleteApiV1CapabilitiesStaleUrl = (
  params?: DeleteApiV1CapabilitiesStaleParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/capabilities/stale?${stringifiedParams}`
    : `/api/v1/capabilities/stale`;
};

export const deleteApiV1CapabilitiesStale = async (
  params?: DeleteApiV1CapabilitiesStaleParams,
  options?: RequestInit,
): Promise<deleteApiV1CapabilitiesStaleResponse> => {
  return customFetch<deleteApiV1CapabilitiesStaleResponse>(
    getDeleteApiV1CapabilitiesStaleUrl(params),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Tools State
 */
export type getApiV1CapabilitiesToolsStateResponse200 = {
  data: WanakuResponseMapStringListActivityRecord;
  status: 200;
};

export type getApiV1CapabilitiesToolsStateResponseSuccess =
  getApiV1CapabilitiesToolsStateResponse200 & {
    headers: Headers;
  };
export type getApiV1CapabilitiesToolsStateResponse =
  getApiV1CapabilitiesToolsStateResponseSuccess;

export const getGetApiV1CapabilitiesToolsStateUrl = () => {
  return `/api/v1/capabilities/tools/state`;
};

export const getApiV1CapabilitiesToolsState = async (
  options?: RequestInit,
): Promise<getApiV1CapabilitiesToolsStateResponse> => {
  return customFetch<getApiV1CapabilitiesToolsStateResponse>(
    getGetApiV1CapabilitiesToolsStateUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update
 */
export type putApiV1DataStoreResponse200 = {
  data: void;
  status: 200;
};

export type putApiV1DataStoreResponse400 = {
  data: void;
  status: 400;
};

export type putApiV1DataStoreResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type putApiV1DataStoreResponseSuccess = putApiV1DataStoreResponse200 & {
  headers: Headers;
};
export type putApiV1DataStoreResponseError = (
  | putApiV1DataStoreResponse400
  | putApiV1DataStoreResponse500
) & {
  headers: Headers;
};

export type putApiV1DataStoreResponse =
  | putApiV1DataStoreResponseSuccess
  | putApiV1DataStoreResponseError;

export const getPutApiV1DataStoreUrl = () => {
  return `/api/v1/data-store`;
};

export const putApiV1DataStore = async (
  dataStore: DataStore,
  options?: RequestInit,
): Promise<putApiV1DataStoreResponse> => {
  return customFetch<putApiV1DataStoreResponse>(getPutApiV1DataStoreUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(dataStore),
  });
};

/**
 * @summary Remove By Name
 */
export type deleteApiV1DataStoreResponse200 = {
  data: void;
  status: 200;
};

export type deleteApiV1DataStoreResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type deleteApiV1DataStoreResponseSuccess =
  deleteApiV1DataStoreResponse200 & {
    headers: Headers;
  };
export type deleteApiV1DataStoreResponseError =
  deleteApiV1DataStoreResponse500 & {
    headers: Headers;
  };

export type deleteApiV1DataStoreResponse =
  | deleteApiV1DataStoreResponseSuccess
  | deleteApiV1DataStoreResponseError;

export const getDeleteApiV1DataStoreUrl = (
  params?: DeleteApiV1DataStoreParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/data-store?${stringifiedParams}`
    : `/api/v1/data-store`;
};

export const deleteApiV1DataStore = async (
  params?: DeleteApiV1DataStoreParams,
  options?: RequestInit,
): Promise<deleteApiV1DataStoreResponse> => {
  return customFetch<deleteApiV1DataStoreResponse>(
    getDeleteApiV1DataStoreUrl(params),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary List Or Get By Name
 */
export type getApiV1DataStoreResponse200 = {
  data: WanakuResponseListDataStore;
  status: 200;
};

export type getApiV1DataStoreResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type getApiV1DataStoreResponseSuccess = getApiV1DataStoreResponse200 & {
  headers: Headers;
};
export type getApiV1DataStoreResponseError = getApiV1DataStoreResponse500 & {
  headers: Headers;
};

export type getApiV1DataStoreResponse =
  | getApiV1DataStoreResponseSuccess
  | getApiV1DataStoreResponseError;

export const getGetApiV1DataStoreUrl = (params?: GetApiV1DataStoreParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/data-store?${stringifiedParams}`
    : `/api/v1/data-store`;
};

export const getApiV1DataStore = async (
  params?: GetApiV1DataStoreParams,
  options?: RequestInit,
): Promise<getApiV1DataStoreResponse> => {
  return customFetch<getApiV1DataStoreResponse>(
    getGetApiV1DataStoreUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Add
 */
export type postApiV1DataStoreResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type postApiV1DataStoreResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1DataStoreResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type postApiV1DataStoreResponseSuccess =
  postApiV1DataStoreResponse200 & {
    headers: Headers;
  };
export type postApiV1DataStoreResponseError = (
  | postApiV1DataStoreResponse400
  | postApiV1DataStoreResponse500
) & {
  headers: Headers;
};

export type postApiV1DataStoreResponse =
  | postApiV1DataStoreResponseSuccess
  | postApiV1DataStoreResponseError;

export const getPostApiV1DataStoreUrl = () => {
  return `/api/v1/data-store`;
};

export const postApiV1DataStore = async (
  dataStore: DataStore,
  options?: RequestInit,
): Promise<postApiV1DataStoreResponse> => {
  return customFetch<postApiV1DataStoreResponse>(getPostApiV1DataStoreUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(dataStore),
  });
};

/**
 * @summary Remove If
 */
export type deleteApiV1DataStoreLabelsResponse200 = {
  data: WanakuResponseInteger;
  status: 200;
};

export type deleteApiV1DataStoreLabelsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type deleteApiV1DataStoreLabelsResponseSuccess =
  deleteApiV1DataStoreLabelsResponse200 & {
    headers: Headers;
  };
export type deleteApiV1DataStoreLabelsResponseError =
  deleteApiV1DataStoreLabelsResponse500 & {
    headers: Headers;
  };

export type deleteApiV1DataStoreLabelsResponse =
  | deleteApiV1DataStoreLabelsResponseSuccess
  | deleteApiV1DataStoreLabelsResponseError;

export const getDeleteApiV1DataStoreLabelsUrl = (
  params?: DeleteApiV1DataStoreLabelsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/data-store/labels?${stringifiedParams}`
    : `/api/v1/data-store/labels`;
};

export const deleteApiV1DataStoreLabels = async (
  params?: DeleteApiV1DataStoreLabelsParams,
  options?: RequestInit,
): Promise<deleteApiV1DataStoreLabelsResponse> => {
  return customFetch<deleteApiV1DataStoreLabelsResponse>(
    getDeleteApiV1DataStoreLabelsUrl(params),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Remove By Id
 */
export type deleteApiV1DataStoreIdResponse200 = {
  data: void;
  status: 200;
};

export type deleteApiV1DataStoreIdResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type deleteApiV1DataStoreIdResponseSuccess =
  deleteApiV1DataStoreIdResponse200 & {
    headers: Headers;
  };
export type deleteApiV1DataStoreIdResponseError =
  deleteApiV1DataStoreIdResponse500 & {
    headers: Headers;
  };

export type deleteApiV1DataStoreIdResponse =
  | deleteApiV1DataStoreIdResponseSuccess
  | deleteApiV1DataStoreIdResponseError;

export const getDeleteApiV1DataStoreIdUrl = (id: string) => {
  return `/api/v1/data-store/${id}`;
};

export const deleteApiV1DataStoreId = async (
  id: string,
  options?: RequestInit,
): Promise<deleteApiV1DataStoreIdResponse> => {
  return customFetch<deleteApiV1DataStoreIdResponse>(
    getDeleteApiV1DataStoreIdUrl(id),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Get By Id
 */
export type getApiV1DataStoreIdResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type getApiV1DataStoreIdResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type getApiV1DataStoreIdResponseSuccess =
  getApiV1DataStoreIdResponse200 & {
    headers: Headers;
  };
export type getApiV1DataStoreIdResponseError =
  getApiV1DataStoreIdResponse500 & {
    headers: Headers;
  };

export type getApiV1DataStoreIdResponse =
  | getApiV1DataStoreIdResponseSuccess
  | getApiV1DataStoreIdResponseError;

export const getGetApiV1DataStoreIdUrl = (id: string) => {
  return `/api/v1/data-store/${id}`;
};

export const getApiV1DataStoreId = async (
  id: string,
  options?: RequestInit,
): Promise<getApiV1DataStoreIdResponse> => {
  return customFetch<getApiV1DataStoreIdResponse>(
    getGetApiV1DataStoreIdUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary List Forwards
 */
export type getApiV1ForwardsResponse200 = {
  data: WanakuResponseListForwardReference;
  status: 200;
};

export type getApiV1ForwardsResponseSuccess = getApiV1ForwardsResponse200 & {
  headers: Headers;
};
export type getApiV1ForwardsResponse = getApiV1ForwardsResponseSuccess;

export const getGetApiV1ForwardsUrl = (params?: GetApiV1ForwardsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/forwards?${stringifiedParams}`
    : `/api/v1/forwards`;
};

export const getApiV1Forwards = async (
  params?: GetApiV1ForwardsParams,
  options?: RequestInit,
): Promise<getApiV1ForwardsResponse> => {
  return customFetch<getApiV1ForwardsResponse>(getGetApiV1ForwardsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Add Forward
 */
export type postApiV1ForwardsResponse200 = {
  data: void;
  status: 200;
};

export type postApiV1ForwardsResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1ForwardsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type postApiV1ForwardsResponseSuccess = postApiV1ForwardsResponse200 & {
  headers: Headers;
};
export type postApiV1ForwardsResponseError = (
  | postApiV1ForwardsResponse400
  | postApiV1ForwardsResponse500
) & {
  headers: Headers;
};

export type postApiV1ForwardsResponse =
  | postApiV1ForwardsResponseSuccess
  | postApiV1ForwardsResponseError;

export const getPostApiV1ForwardsUrl = () => {
  return `/api/v1/forwards`;
};

export const postApiV1Forwards = async (
  forwardReference: ForwardReference,
  options?: RequestInit,
): Promise<postApiV1ForwardsResponse> => {
  return customFetch<postApiV1ForwardsResponse>(getPostApiV1ForwardsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(forwardReference),
  });
};

/**
 * @summary Update
 */
export type putApiV1ForwardsNameResponse200 = {
  data: void;
  status: 200;
};

export type putApiV1ForwardsNameResponse400 = {
  data: void;
  status: 400;
};

export type putApiV1ForwardsNameResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type putApiV1ForwardsNameResponseSuccess =
  putApiV1ForwardsNameResponse200 & {
    headers: Headers;
  };
export type putApiV1ForwardsNameResponseError = (
  | putApiV1ForwardsNameResponse400
  | putApiV1ForwardsNameResponse500
) & {
  headers: Headers;
};

export type putApiV1ForwardsNameResponse =
  | putApiV1ForwardsNameResponseSuccess
  | putApiV1ForwardsNameResponseError;

export const getPutApiV1ForwardsNameUrl = (name: string) => {
  return `/api/v1/forwards/${name}`;
};

export const putApiV1ForwardsName = async (
  name: string,
  forwardReference: ForwardReference,
  options?: RequestInit,
): Promise<putApiV1ForwardsNameResponse> => {
  return customFetch<putApiV1ForwardsNameResponse>(
    getPutApiV1ForwardsNameUrl(name),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(forwardReference),
    },
  );
};

/**
 * @summary Remove Forward
 */
export type deleteApiV1ForwardsNameResponse200 = {
  data: void;
  status: 200;
};

export type deleteApiV1ForwardsNameResponseSuccess =
  deleteApiV1ForwardsNameResponse200 & {
    headers: Headers;
  };
export type deleteApiV1ForwardsNameResponse =
  deleteApiV1ForwardsNameResponseSuccess;

export const getDeleteApiV1ForwardsNameUrl = (name: string) => {
  return `/api/v1/forwards/${name}`;
};

export const deleteApiV1ForwardsName = async (
  name: string,
  options?: RequestInit,
): Promise<deleteApiV1ForwardsNameResponse> => {
  return customFetch<deleteApiV1ForwardsNameResponse>(
    getDeleteApiV1ForwardsNameUrl(name),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Get By Name
 */
export type getApiV1ForwardsNameResponse200 = {
  data: WanakuResponseForwardReference;
  status: 200;
};

export type getApiV1ForwardsNameResponseSuccess =
  getApiV1ForwardsNameResponse200 & {
    headers: Headers;
  };
export type getApiV1ForwardsNameResponse = getApiV1ForwardsNameResponseSuccess;

export const getGetApiV1ForwardsNameUrl = (name: string) => {
  return `/api/v1/forwards/${name}`;
};

export const getApiV1ForwardsName = async (
  name: string,
  options?: RequestInit,
): Promise<getApiV1ForwardsNameResponse> => {
  return customFetch<getApiV1ForwardsNameResponse>(
    getGetApiV1ForwardsNameUrl(name),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Refresh
 */
export type postApiV1ForwardsNameRefreshesResponse200 = {
  data: void;
  status: 200;
};

export type postApiV1ForwardsNameRefreshesResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type postApiV1ForwardsNameRefreshesResponseSuccess =
  postApiV1ForwardsNameRefreshesResponse200 & {
    headers: Headers;
  };
export type postApiV1ForwardsNameRefreshesResponseError =
  postApiV1ForwardsNameRefreshesResponse500 & {
    headers: Headers;
  };

export type postApiV1ForwardsNameRefreshesResponse =
  | postApiV1ForwardsNameRefreshesResponseSuccess
  | postApiV1ForwardsNameRefreshesResponseError;

export const getPostApiV1ForwardsNameRefreshesUrl = (name: string) => {
  return `/api/v1/forwards/${name}/refreshes`;
};

export const postApiV1ForwardsNameRefreshes = async (
  name: string,
  options?: RequestInit,
): Promise<postApiV1ForwardsNameRefreshesResponse> => {
  return customFetch<postApiV1ForwardsNameRefreshesResponse>(
    getPostApiV1ForwardsNameRefreshesUrl(name),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Register
 */
export type postApiV1ManagementDiscoveryResponse200 = {
  data: WanakuResponseServiceTarget;
  status: 200;
};

export type postApiV1ManagementDiscoveryResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1ManagementDiscoveryResponseSuccess =
  postApiV1ManagementDiscoveryResponse200 & {
    headers: Headers;
  };
export type postApiV1ManagementDiscoveryResponseError =
  postApiV1ManagementDiscoveryResponse400 & {
    headers: Headers;
  };

export type postApiV1ManagementDiscoveryResponse =
  | postApiV1ManagementDiscoveryResponseSuccess
  | postApiV1ManagementDiscoveryResponseError;

export const getPostApiV1ManagementDiscoveryUrl = () => {
  return `/api/v1/management/discovery`;
};

export const postApiV1ManagementDiscovery = async (
  serviceTarget: ServiceTarget,
  options?: RequestInit,
): Promise<postApiV1ManagementDiscoveryResponse> => {
  return customFetch<postApiV1ManagementDiscoveryResponse>(
    getPostApiV1ManagementDiscoveryUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(serviceTarget),
    },
  );
};

/**
 * @summary Deregister
 */
export type deleteApiV1ManagementDiscoveryResponse200 = {
  data: void;
  status: 200;
};

export type deleteApiV1ManagementDiscoveryResponseSuccess =
  deleteApiV1ManagementDiscoveryResponse200 & {
    headers: Headers;
  };
export type deleteApiV1ManagementDiscoveryResponse =
  deleteApiV1ManagementDiscoveryResponseSuccess;

export const getDeleteApiV1ManagementDiscoveryUrl = () => {
  return `/api/v1/management/discovery`;
};

export const deleteApiV1ManagementDiscovery = async (
  serviceTarget: ServiceTarget,
  options?: RequestInit,
): Promise<deleteApiV1ManagementDiscoveryResponse> => {
  return customFetch<deleteApiV1ManagementDiscoveryResponse>(
    getDeleteApiV1ManagementDiscoveryUrl(),
    {
      ...options,
      method: "DELETE",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(serviceTarget),
    },
  );
};

/**
 * @deprecated
 * @summary Ping
 */
export type postApiV1ManagementDiscoveryHeartbeatsResponse200 = {
  data: void;
  status: 200;
};

export type postApiV1ManagementDiscoveryHeartbeatsResponseSuccess =
  postApiV1ManagementDiscoveryHeartbeatsResponse200 & {
    headers: Headers;
  };
export type postApiV1ManagementDiscoveryHeartbeatsResponse =
  postApiV1ManagementDiscoveryHeartbeatsResponseSuccess;

export const getPostApiV1ManagementDiscoveryHeartbeatsUrl = () => {
  return `/api/v1/management/discovery/heartbeats`;
};

export const postApiV1ManagementDiscoveryHeartbeats = async (
  postApiV1ManagementDiscoveryHeartbeatsBody: string,
  options?: RequestInit,
): Promise<postApiV1ManagementDiscoveryHeartbeatsResponse> => {
  return customFetch<postApiV1ManagementDiscoveryHeartbeatsResponse>(
    getPostApiV1ManagementDiscoveryHeartbeatsUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(postApiV1ManagementDiscoveryHeartbeatsBody),
    },
  );
};

/**
 * @summary Version
 */
export type getApiV1ManagementInfoVersionResponse200 = {
  data: WanakuResponseServerInfo;
  status: 200;
};

export type getApiV1ManagementInfoVersionResponseSuccess =
  getApiV1ManagementInfoVersionResponse200 & {
    headers: Headers;
  };
export type getApiV1ManagementInfoVersionResponse =
  getApiV1ManagementInfoVersionResponseSuccess;

export const getGetApiV1ManagementInfoVersionUrl = () => {
  return `/api/v1/management/info/version`;
};

export const getApiV1ManagementInfoVersion = async (
  options?: RequestInit,
): Promise<getApiV1ManagementInfoVersionResponse> => {
  return customFetch<getApiV1ManagementInfoVersionResponse>(
    getGetApiV1ManagementInfoVersionUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get Statistics
 */
export type getApiV1ManagementStatisticsResponse200 = {
  data: WanakuResponseSystemStatistics;
  status: 200;
};

export type getApiV1ManagementStatisticsResponseSuccess =
  getApiV1ManagementStatisticsResponse200 & {
    headers: Headers;
  };
export type getApiV1ManagementStatisticsResponse =
  getApiV1ManagementStatisticsResponseSuccess;

export const getGetApiV1ManagementStatisticsUrl = () => {
  return `/api/v1/management/statistics`;
};

export const getApiV1ManagementStatistics = async (
  options?: RequestInit,
): Promise<getApiV1ManagementStatisticsResponse> => {
  return customFetch<getApiV1ManagementStatisticsResponse>(
    getGetApiV1ManagementStatisticsUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary List
 */
export type getApiV1NamespacesResponse200 = {
  data: WanakuResponseListNamespace;
  status: 200;
};

export type getApiV1NamespacesResponseSuccess =
  getApiV1NamespacesResponse200 & {
    headers: Headers;
  };
export type getApiV1NamespacesResponse = getApiV1NamespacesResponseSuccess;

export const getGetApiV1NamespacesUrl = (params?: GetApiV1NamespacesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/namespaces?${stringifiedParams}`
    : `/api/v1/namespaces`;
};

export const getApiV1Namespaces = async (
  params?: GetApiV1NamespacesParams,
  options?: RequestInit,
): Promise<getApiV1NamespacesResponse> => {
  return customFetch<getApiV1NamespacesResponse>(
    getGetApiV1NamespacesUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update
 */
export type putApiV1NamespacesIdResponse200 = {
  data: void;
  status: 200;
};

export type putApiV1NamespacesIdResponse400 = {
  data: void;
  status: 400;
};

export type putApiV1NamespacesIdResponseSuccess =
  putApiV1NamespacesIdResponse200 & {
    headers: Headers;
  };
export type putApiV1NamespacesIdResponseError =
  putApiV1NamespacesIdResponse400 & {
    headers: Headers;
  };

export type putApiV1NamespacesIdResponse =
  | putApiV1NamespacesIdResponseSuccess
  | putApiV1NamespacesIdResponseError;

export const getPutApiV1NamespacesIdUrl = (id: string) => {
  return `/api/v1/namespaces/${id}`;
};

export const putApiV1NamespacesId = async (
  id: string,
  namespace: Namespace,
  options?: RequestInit,
): Promise<putApiV1NamespacesIdResponse> => {
  return customFetch<putApiV1NamespacesIdResponse>(
    getPutApiV1NamespacesIdUrl(id),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(namespace),
    },
  );
};

/**
 * @summary Get By Id
 */
export type getApiV1NamespacesIdResponse200 = {
  data: WanakuResponseNamespace;
  status: 200;
};

export type getApiV1NamespacesIdResponseSuccess =
  getApiV1NamespacesIdResponse200 & {
    headers: Headers;
  };
export type getApiV1NamespacesIdResponse = getApiV1NamespacesIdResponseSuccess;

export const getGetApiV1NamespacesIdUrl = (id: string) => {
  return `/api/v1/namespaces/${id}`;
};

export const getApiV1NamespacesId = async (
  id: string,
  options?: RequestInit,
): Promise<getApiV1NamespacesIdResponse> => {
  return customFetch<getApiV1NamespacesIdResponse>(
    getGetApiV1NamespacesIdUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update
 */
export type putApiV1PromptsResponse200 = {
  data: void;
  status: 200;
};

export type putApiV1PromptsResponse400 = {
  data: void;
  status: 400;
};

export type putApiV1PromptsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type putApiV1PromptsResponseSuccess = putApiV1PromptsResponse200 & {
  headers: Headers;
};
export type putApiV1PromptsResponseError = (
  | putApiV1PromptsResponse400
  | putApiV1PromptsResponse500
) & {
  headers: Headers;
};

export type putApiV1PromptsResponse =
  | putApiV1PromptsResponseSuccess
  | putApiV1PromptsResponseError;

export const getPutApiV1PromptsUrl = () => {
  return `/api/v1/prompts`;
};

export const putApiV1Prompts = async (
  promptReference: PromptReference,
  options?: RequestInit,
): Promise<putApiV1PromptsResponse> => {
  return customFetch<putApiV1PromptsResponse>(getPutApiV1PromptsUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(promptReference),
  });
};

/**
 * @summary Remove
 */
export type deleteApiV1PromptsResponse200 = {
  data: void;
  status: 200;
};

export type deleteApiV1PromptsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type deleteApiV1PromptsResponseSuccess =
  deleteApiV1PromptsResponse200 & {
    headers: Headers;
  };
export type deleteApiV1PromptsResponseError = deleteApiV1PromptsResponse500 & {
  headers: Headers;
};

export type deleteApiV1PromptsResponse =
  | deleteApiV1PromptsResponseSuccess
  | deleteApiV1PromptsResponseError;

export const getDeleteApiV1PromptsUrl = (params?: DeleteApiV1PromptsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/prompts?${stringifiedParams}`
    : `/api/v1/prompts`;
};

export const deleteApiV1Prompts = async (
  params?: DeleteApiV1PromptsParams,
  options?: RequestInit,
): Promise<deleteApiV1PromptsResponse> => {
  return customFetch<deleteApiV1PromptsResponse>(
    getDeleteApiV1PromptsUrl(params),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary List
 */
export type getApiV1PromptsResponse200 = {
  data: WanakuResponseListPromptReference;
  status: 200;
};

export type getApiV1PromptsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type getApiV1PromptsResponseSuccess = getApiV1PromptsResponse200 & {
  headers: Headers;
};
export type getApiV1PromptsResponseError = getApiV1PromptsResponse500 & {
  headers: Headers;
};

export type getApiV1PromptsResponse =
  | getApiV1PromptsResponseSuccess
  | getApiV1PromptsResponseError;

export const getGetApiV1PromptsUrl = () => {
  return `/api/v1/prompts`;
};

export const getApiV1Prompts = async (
  options?: RequestInit,
): Promise<getApiV1PromptsResponse> => {
  return customFetch<getApiV1PromptsResponse>(getGetApiV1PromptsUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Add
 */
export type postApiV1PromptsResponse200 = {
  data: WanakuResponsePromptReference;
  status: 200;
};

export type postApiV1PromptsResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1PromptsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type postApiV1PromptsResponseSuccess = postApiV1PromptsResponse200 & {
  headers: Headers;
};
export type postApiV1PromptsResponseError = (
  | postApiV1PromptsResponse400
  | postApiV1PromptsResponse500
) & {
  headers: Headers;
};

export type postApiV1PromptsResponse =
  | postApiV1PromptsResponseSuccess
  | postApiV1PromptsResponseError;

export const getPostApiV1PromptsUrl = () => {
  return `/api/v1/prompts`;
};

export const postApiV1Prompts = async (
  promptReference: PromptReference,
  options?: RequestInit,
): Promise<postApiV1PromptsResponse> => {
  return customFetch<postApiV1PromptsResponse>(getPostApiV1PromptsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(promptReference),
  });
};

/**
 * @summary Add With Payload
 */
export type postApiV1PromptsPayloadsResponse200 = {
  data: WanakuResponsePromptReference;
  status: 200;
};

export type postApiV1PromptsPayloadsResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1PromptsPayloadsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type postApiV1PromptsPayloadsResponseSuccess =
  postApiV1PromptsPayloadsResponse200 & {
    headers: Headers;
  };
export type postApiV1PromptsPayloadsResponseError = (
  | postApiV1PromptsPayloadsResponse400
  | postApiV1PromptsPayloadsResponse500
) & {
  headers: Headers;
};

export type postApiV1PromptsPayloadsResponse =
  | postApiV1PromptsPayloadsResponseSuccess
  | postApiV1PromptsPayloadsResponseError;

export const getPostApiV1PromptsPayloadsUrl = () => {
  return `/api/v1/prompts/payloads`;
};

export const postApiV1PromptsPayloads = async (
  promptPayload: PromptPayload,
  options?: RequestInit,
): Promise<postApiV1PromptsPayloadsResponse> => {
  return customFetch<postApiV1PromptsPayloadsResponse>(
    getPostApiV1PromptsPayloadsUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(promptPayload),
    },
  );
};

/**
 * @summary Get By Name
 */
export type getApiV1PromptsNameResponse200 = {
  data: WanakuResponsePromptReference;
  status: 200;
};

export type getApiV1PromptsNameResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type getApiV1PromptsNameResponseSuccess =
  getApiV1PromptsNameResponse200 & {
    headers: Headers;
  };
export type getApiV1PromptsNameResponseError =
  getApiV1PromptsNameResponse500 & {
    headers: Headers;
  };

export type getApiV1PromptsNameResponse =
  | getApiV1PromptsNameResponseSuccess
  | getApiV1PromptsNameResponseError;

export const getGetApiV1PromptsNameUrl = (name: string) => {
  return `/api/v1/prompts/${name}`;
};

export const getApiV1PromptsName = async (
  name: string,
  options?: RequestInit,
): Promise<getApiV1PromptsNameResponse> => {
  return customFetch<getApiV1PromptsNameResponse>(
    getGetApiV1PromptsNameUrl(name),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary List
 */
export type getApiV1ResourcesResponse200 = {
  data: WanakuResponseListResourceReference;
  status: 200;
};

export type getApiV1ResourcesResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type getApiV1ResourcesResponseSuccess = getApiV1ResourcesResponse200 & {
  headers: Headers;
};
export type getApiV1ResourcesResponseError = getApiV1ResourcesResponse500 & {
  headers: Headers;
};

export type getApiV1ResourcesResponse =
  | getApiV1ResourcesResponseSuccess
  | getApiV1ResourcesResponseError;

export const getGetApiV1ResourcesUrl = (params?: GetApiV1ResourcesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/resources?${stringifiedParams}`
    : `/api/v1/resources`;
};

export const getApiV1Resources = async (
  params?: GetApiV1ResourcesParams,
  options?: RequestInit,
): Promise<getApiV1ResourcesResponse> => {
  return customFetch<getApiV1ResourcesResponse>(
    getGetApiV1ResourcesUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Expose
 */
export type postApiV1ResourcesResponse200 = {
  data: WanakuResponseResourceReference;
  status: 200;
};

export type postApiV1ResourcesResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1ResourcesResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type postApiV1ResourcesResponseSuccess =
  postApiV1ResourcesResponse200 & {
    headers: Headers;
  };
export type postApiV1ResourcesResponseError = (
  | postApiV1ResourcesResponse400
  | postApiV1ResourcesResponse500
) & {
  headers: Headers;
};

export type postApiV1ResourcesResponse =
  | postApiV1ResourcesResponseSuccess
  | postApiV1ResourcesResponseError;

export const getPostApiV1ResourcesUrl = () => {
  return `/api/v1/resources`;
};

export const postApiV1Resources = async (
  resourceReference: ResourceReference,
  options?: RequestInit,
): Promise<postApiV1ResourcesResponse> => {
  return customFetch<postApiV1ResourcesResponse>(getPostApiV1ResourcesUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(resourceReference),
  });
};

/**
 * @summary Expose With Payload
 */
export type postApiV1ResourcesPayloadsResponse200 = {
  data: WanakuResponseResourceReference;
  status: 200;
};

export type postApiV1ResourcesPayloadsResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1ResourcesPayloadsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type postApiV1ResourcesPayloadsResponseSuccess =
  postApiV1ResourcesPayloadsResponse200 & {
    headers: Headers;
  };
export type postApiV1ResourcesPayloadsResponseError = (
  | postApiV1ResourcesPayloadsResponse400
  | postApiV1ResourcesPayloadsResponse500
) & {
  headers: Headers;
};

export type postApiV1ResourcesPayloadsResponse =
  | postApiV1ResourcesPayloadsResponseSuccess
  | postApiV1ResourcesPayloadsResponseError;

export const getPostApiV1ResourcesPayloadsUrl = () => {
  return `/api/v1/resources/payloads`;
};

export const postApiV1ResourcesPayloads = async (
  resourcePayload: ResourcePayload,
  options?: RequestInit,
): Promise<postApiV1ResourcesPayloadsResponse> => {
  return customFetch<postApiV1ResourcesPayloadsResponse>(
    getPostApiV1ResourcesPayloadsUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(resourcePayload),
    },
  );
};

/**
 * @summary Update
 */
export type putApiV1ResourcesNameResponse200 = {
  data: void;
  status: 200;
};

export type putApiV1ResourcesNameResponse400 = {
  data: void;
  status: 400;
};

export type putApiV1ResourcesNameResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type putApiV1ResourcesNameResponseSuccess =
  putApiV1ResourcesNameResponse200 & {
    headers: Headers;
  };
export type putApiV1ResourcesNameResponseError = (
  | putApiV1ResourcesNameResponse400
  | putApiV1ResourcesNameResponse500
) & {
  headers: Headers;
};

export type putApiV1ResourcesNameResponse =
  | putApiV1ResourcesNameResponseSuccess
  | putApiV1ResourcesNameResponseError;

export const getPutApiV1ResourcesNameUrl = (name: string) => {
  return `/api/v1/resources/${name}`;
};

export const putApiV1ResourcesName = async (
  name: string,
  resourceReference: ResourceReference,
  options?: RequestInit,
): Promise<putApiV1ResourcesNameResponse> => {
  return customFetch<putApiV1ResourcesNameResponse>(
    getPutApiV1ResourcesNameUrl(name),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(resourceReference),
    },
  );
};

/**
 * @summary Remove
 */
export type deleteApiV1ResourcesNameResponse200 = {
  data: void;
  status: 200;
};

export type deleteApiV1ResourcesNameResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type deleteApiV1ResourcesNameResponseSuccess =
  deleteApiV1ResourcesNameResponse200 & {
    headers: Headers;
  };
export type deleteApiV1ResourcesNameResponseError =
  deleteApiV1ResourcesNameResponse500 & {
    headers: Headers;
  };

export type deleteApiV1ResourcesNameResponse =
  | deleteApiV1ResourcesNameResponseSuccess
  | deleteApiV1ResourcesNameResponseError;

export const getDeleteApiV1ResourcesNameUrl = (name: string) => {
  return `/api/v1/resources/${name}`;
};

export const deleteApiV1ResourcesName = async (
  name: string,
  options?: RequestInit,
): Promise<deleteApiV1ResourcesNameResponse> => {
  return customFetch<deleteApiV1ResourcesNameResponse>(
    getDeleteApiV1ResourcesNameUrl(name),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Get By Name
 */
export type getApiV1ResourcesNameResponse200 = {
  data: WanakuResponseResourceReference;
  status: 200;
};

export type getApiV1ResourcesNameResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type getApiV1ResourcesNameResponseSuccess =
  getApiV1ResourcesNameResponse200 & {
    headers: Headers;
  };
export type getApiV1ResourcesNameResponseError =
  getApiV1ResourcesNameResponse500 & {
    headers: Headers;
  };

export type getApiV1ResourcesNameResponse =
  | getApiV1ResourcesNameResponseSuccess
  | getApiV1ResourcesNameResponseError;

export const getGetApiV1ResourcesNameUrl = (name: string) => {
  return `/api/v1/resources/${name}`;
};

export const getApiV1ResourcesName = async (
  name: string,
  options?: RequestInit,
): Promise<getApiV1ResourcesNameResponse> => {
  return customFetch<getApiV1ResourcesNameResponse>(
    getGetApiV1ResourcesNameUrl(name),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Remove If
 */
export type deleteApiV1ToolsResponse200 = {
  data: WanakuResponseInteger;
  status: 200;
};

export type deleteApiV1ToolsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type deleteApiV1ToolsResponseSuccess = deleteApiV1ToolsResponse200 & {
  headers: Headers;
};
export type deleteApiV1ToolsResponseError = deleteApiV1ToolsResponse500 & {
  headers: Headers;
};

export type deleteApiV1ToolsResponse =
  | deleteApiV1ToolsResponseSuccess
  | deleteApiV1ToolsResponseError;

export const getDeleteApiV1ToolsUrl = (params?: DeleteApiV1ToolsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/tools?${stringifiedParams}`
    : `/api/v1/tools`;
};

export const deleteApiV1Tools = async (
  params?: DeleteApiV1ToolsParams,
  options?: RequestInit,
): Promise<deleteApiV1ToolsResponse> => {
  return customFetch<deleteApiV1ToolsResponse>(getDeleteApiV1ToolsUrl(params), {
    ...options,
    method: "DELETE",
  });
};

/**
 * @summary List
 */
export type getApiV1ToolsResponse200 = {
  data: WanakuResponseListToolReference;
  status: 200;
};

export type getApiV1ToolsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type getApiV1ToolsResponseSuccess = getApiV1ToolsResponse200 & {
  headers: Headers;
};
export type getApiV1ToolsResponseError = getApiV1ToolsResponse500 & {
  headers: Headers;
};

export type getApiV1ToolsResponse =
  | getApiV1ToolsResponseSuccess
  | getApiV1ToolsResponseError;

export const getGetApiV1ToolsUrl = (params?: GetApiV1ToolsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/tools?${stringifiedParams}`
    : `/api/v1/tools`;
};

export const getApiV1Tools = async (
  params?: GetApiV1ToolsParams,
  options?: RequestInit,
): Promise<getApiV1ToolsResponse> => {
  return customFetch<getApiV1ToolsResponse>(getGetApiV1ToolsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Add
 */
export type postApiV1ToolsResponse200 = {
  data: WanakuResponseToolReference;
  status: 200;
};

export type postApiV1ToolsResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1ToolsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type postApiV1ToolsResponseSuccess = postApiV1ToolsResponse200 & {
  headers: Headers;
};
export type postApiV1ToolsResponseError = (
  | postApiV1ToolsResponse400
  | postApiV1ToolsResponse500
) & {
  headers: Headers;
};

export type postApiV1ToolsResponse =
  | postApiV1ToolsResponseSuccess
  | postApiV1ToolsResponseError;

export const getPostApiV1ToolsUrl = () => {
  return `/api/v1/tools`;
};

export const postApiV1Tools = async (
  toolReference: ToolReference,
  options?: RequestInit,
): Promise<postApiV1ToolsResponse> => {
  return customFetch<postApiV1ToolsResponse>(getPostApiV1ToolsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(toolReference),
  });
};

/**
 * @summary Add With Payload
 */
export type postApiV1ToolsPayloadsResponse200 = {
  data: WanakuResponseToolReference;
  status: 200;
};

export type postApiV1ToolsPayloadsResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1ToolsPayloadsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type postApiV1ToolsPayloadsResponseSuccess =
  postApiV1ToolsPayloadsResponse200 & {
    headers: Headers;
  };
export type postApiV1ToolsPayloadsResponseError = (
  | postApiV1ToolsPayloadsResponse400
  | postApiV1ToolsPayloadsResponse500
) & {
  headers: Headers;
};

export type postApiV1ToolsPayloadsResponse =
  | postApiV1ToolsPayloadsResponseSuccess
  | postApiV1ToolsPayloadsResponseError;

export const getPostApiV1ToolsPayloadsUrl = () => {
  return `/api/v1/tools/payloads`;
};

export const postApiV1ToolsPayloads = async (
  toolPayload: ToolPayload,
  options?: RequestInit,
): Promise<postApiV1ToolsPayloadsResponse> => {
  return customFetch<postApiV1ToolsPayloadsResponse>(
    getPostApiV1ToolsPayloadsUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(toolPayload),
    },
  );
};

/**
 * @summary Update
 */
export type putApiV1ToolsNameResponse200 = {
  data: void;
  status: 200;
};

export type putApiV1ToolsNameResponse400 = {
  data: void;
  status: 400;
};

export type putApiV1ToolsNameResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type putApiV1ToolsNameResponseSuccess = putApiV1ToolsNameResponse200 & {
  headers: Headers;
};
export type putApiV1ToolsNameResponseError = (
  | putApiV1ToolsNameResponse400
  | putApiV1ToolsNameResponse500
) & {
  headers: Headers;
};

export type putApiV1ToolsNameResponse =
  | putApiV1ToolsNameResponseSuccess
  | putApiV1ToolsNameResponseError;

export const getPutApiV1ToolsNameUrl = (name: string) => {
  return `/api/v1/tools/${name}`;
};

export const putApiV1ToolsName = async (
  name: string,
  toolReference: ToolReference,
  options?: RequestInit,
): Promise<putApiV1ToolsNameResponse> => {
  return customFetch<putApiV1ToolsNameResponse>(getPutApiV1ToolsNameUrl(name), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(toolReference),
  });
};

/**
 * @summary Remove
 */
export type deleteApiV1ToolsNameResponse200 = {
  data: void;
  status: 200;
};

export type deleteApiV1ToolsNameResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type deleteApiV1ToolsNameResponseSuccess =
  deleteApiV1ToolsNameResponse200 & {
    headers: Headers;
  };
export type deleteApiV1ToolsNameResponseError =
  deleteApiV1ToolsNameResponse500 & {
    headers: Headers;
  };

export type deleteApiV1ToolsNameResponse =
  | deleteApiV1ToolsNameResponseSuccess
  | deleteApiV1ToolsNameResponseError;

export const getDeleteApiV1ToolsNameUrl = (name: string) => {
  return `/api/v1/tools/${name}`;
};

export const deleteApiV1ToolsName = async (
  name: string,
  options?: RequestInit,
): Promise<deleteApiV1ToolsNameResponse> => {
  return customFetch<deleteApiV1ToolsNameResponse>(
    getDeleteApiV1ToolsNameUrl(name),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Get By Name
 */
export type getApiV1ToolsNameResponse200 = {
  data: WanakuResponseToolReference;
  status: 200;
};

export type getApiV1ToolsNameResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type getApiV1ToolsNameResponseSuccess = getApiV1ToolsNameResponse200 & {
  headers: Headers;
};
export type getApiV1ToolsNameResponseError = getApiV1ToolsNameResponse500 & {
  headers: Headers;
};

export type getApiV1ToolsNameResponse =
  | getApiV1ToolsNameResponseSuccess
  | getApiV1ToolsNameResponseError;

export const getGetApiV1ToolsNameUrl = (name: string) => {
  return `/api/v1/tools/${name}`;
};

export const getApiV1ToolsName = async (
  name: string,
  options?: RequestInit,
): Promise<getApiV1ToolsNameResponse> => {
  return customFetch<getApiV1ToolsNameResponse>(getGetApiV1ToolsNameUrl(name), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Submit Code
 */
export type postApiV2CodeExecutionEngineEngineTypeLanguageResponse201 = {
  data: CodeExecutionResponse;
  status: 201;
};

export type postApiV2CodeExecutionEngineEngineTypeLanguageResponse400 = {
  data: CodeExecutionError;
  status: 400;
};

export type postApiV2CodeExecutionEngineEngineTypeLanguageResponse500 = {
  data: CodeExecutionError;
  status: 500;
};

export type postApiV2CodeExecutionEngineEngineTypeLanguageResponseSuccess =
  postApiV2CodeExecutionEngineEngineTypeLanguageResponse201 & {
    headers: Headers;
  };
export type postApiV2CodeExecutionEngineEngineTypeLanguageResponseError = (
  | postApiV2CodeExecutionEngineEngineTypeLanguageResponse400
  | postApiV2CodeExecutionEngineEngineTypeLanguageResponse500
) & {
  headers: Headers;
};

export type postApiV2CodeExecutionEngineEngineTypeLanguageResponse =
  | postApiV2CodeExecutionEngineEngineTypeLanguageResponseSuccess
  | postApiV2CodeExecutionEngineEngineTypeLanguageResponseError;

export const getPostApiV2CodeExecutionEngineEngineTypeLanguageUrl = (
  engineType: string,
  language: string,
) => {
  return `/api/v2/code-execution-engine/${engineType}/${language}`;
};

export const postApiV2CodeExecutionEngineEngineTypeLanguage = async (
  engineType: string,
  language: string,
  codeExecutionRequest: CodeExecutionRequest,
  options?: RequestInit,
): Promise<postApiV2CodeExecutionEngineEngineTypeLanguageResponse> => {
  return customFetch<postApiV2CodeExecutionEngineEngineTypeLanguageResponse>(
    getPostApiV2CodeExecutionEngineEngineTypeLanguageUrl(engineType, language),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(codeExecutionRequest),
    },
  );
};

/**
 * @summary Stream Results
 */
export type getApiV2CodeExecutionEngineEngineTypeLanguageTaskIdResponse200 = {
  data: OutboundSseEvent[];
  status: 200;
};

export type getApiV2CodeExecutionEngineEngineTypeLanguageTaskIdResponseSuccess =
  getApiV2CodeExecutionEngineEngineTypeLanguageTaskIdResponse200 & {
    headers: Headers;
  };
export type getApiV2CodeExecutionEngineEngineTypeLanguageTaskIdResponse =
  getApiV2CodeExecutionEngineEngineTypeLanguageTaskIdResponseSuccess;

export const getGetApiV2CodeExecutionEngineEngineTypeLanguageTaskIdUrl = (
  engineType: string,
  language: string,
  taskId: string,
) => {
  return `/api/v2/code-execution-engine/${engineType}/${language}/${taskId}`;
};

export const getApiV2CodeExecutionEngineEngineTypeLanguageTaskId = async (
  engineType: string,
  language: string,
  taskId: string,
  options?: RequestInit,
): Promise<getApiV2CodeExecutionEngineEngineTypeLanguageTaskIdResponse> => {
  return customFetch<getApiV2CodeExecutionEngineEngineTypeLanguageTaskIdResponse>(
    getGetApiV2CodeExecutionEngineEngineTypeLanguageTaskIdUrl(
      engineType,
      language,
      taskId,
    ),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Stream All Tool Calls
 */
export type getApiV2ToolCallsNotificationsResponse200 = {
  data: OutboundSseEvent[];
  status: 200;
};

export type getApiV2ToolCallsNotificationsResponseSuccess =
  getApiV2ToolCallsNotificationsResponse200 & {
    headers: Headers;
  };
export type getApiV2ToolCallsNotificationsResponse =
  getApiV2ToolCallsNotificationsResponseSuccess;

export const getGetApiV2ToolCallsNotificationsUrl = () => {
  return `/api/v2/tool-calls/notifications`;
};

export const getApiV2ToolCallsNotifications = async (
  options?: RequestInit,
): Promise<getApiV2ToolCallsNotificationsResponse> => {
  return customFetch<getApiV2ToolCallsNotificationsResponse>(
    getGetApiV2ToolCallsNotificationsUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Stream Tool Calls By Connection
 */
export type getApiV2ToolCallsNotificationsConnectionIdResponse200 = {
  data: OutboundSseEvent[];
  status: 200;
};

export type getApiV2ToolCallsNotificationsConnectionIdResponseSuccess =
  getApiV2ToolCallsNotificationsConnectionIdResponse200 & {
    headers: Headers;
  };
export type getApiV2ToolCallsNotificationsConnectionIdResponse =
  getApiV2ToolCallsNotificationsConnectionIdResponseSuccess;

export const getGetApiV2ToolCallsNotificationsConnectionIdUrl = (
  connectionId: string,
) => {
  return `/api/v2/tool-calls/notifications/${connectionId}`;
};

export const getApiV2ToolCallsNotificationsConnectionId = async (
  connectionId: string,
  options?: RequestInit,
): Promise<getApiV2ToolCallsNotificationsConnectionIdResponse> => {
  return customFetch<getApiV2ToolCallsNotificationsConnectionIdResponse>(
    getGetApiV2ToolCallsNotificationsConnectionIdUrl(connectionId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Open Id Configuration
 */
export type getTestOidcWellKnownOpenidConfigurationResponse200 = {
  data: string;
  status: 200;
};

export type getTestOidcWellKnownOpenidConfigurationResponseComposite =
  getTestOidcWellKnownOpenidConfigurationResponse200;

export type getTestOidcWellKnownOpenidConfigurationResponse =
  getTestOidcWellKnownOpenidConfigurationResponseComposite & {
    headers: Headers;
  };

export const getGetTestOidcWellKnownOpenidConfigurationUrl = () => {
  return `/test-oidc/.well-known/openid-configuration`;
};

export const getTestOidcWellKnownOpenidConfiguration = async (
  options?: RequestInit,
): Promise<getTestOidcWellKnownOpenidConfigurationResponse> => {
  return customFetch<getTestOidcWellKnownOpenidConfigurationResponse>(
    getGetTestOidcWellKnownOpenidConfigurationUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};
