apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: camel-integration-capability-service
  name: camel-integration-capability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camel-integration-capability
  template:
    metadata:
      labels:
        app: camel-integration-capability
    spec:
      containers:
      - name: camel-integration-capability
        image: quay.io/wanaku/camel-integration-capability:latest
        env:
        - name: REGISTRATION_URL
          value: ""
        - name: REGISTRATION_ANNOUNCE_ADDRESS
          value: "auto"
        - name: GRPC_PORT
          value: "9190"
        - name: SERVICE_NAME
          value: ""
        - name: ROUTES_PATH
          value: ""
        - name: ROUTES_RULES
          value: ""
        - name: SERVICE_CATALOG
          value: ""
        - name: SERVICE_CATALOG_SYSTEM
          value: ""
        - name: TOKEN_ENDPOINT
          value: ""
        - name: CLIENT_ID
          value: "wanaku-service"
        - name: CLIENT_SECRET
          value: ""
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /q/health/live
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        ports:
        - containerPort: 9190
          name: grpc
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        volumeMounts:
          - mountPath: /data
            name: ""
      volumes:
        - name: ""
          persistentVolumeClaim:
            claimName: ""
