catalog.dependencies.kafka=kafka/kafka.dependencies.txt
catalog.description=Send and receive correlated messages via Apache Kafka
catalog.name=kafka-tool
catalog.properties.kafka=kafka/service.properties
catalog.routes.kafka=kafka/kafka.camel.yaml
catalog.rules.kafka=kafka/kafka.rules.yaml
catalog.services=kafka
catalog.versions=versions.properties
