catalog.dependencies.jms=jms/jms.dependencies.txt
catalog.description=Send and receive messages using JMS
catalog.name=jms-tool
catalog.properties.jms=jms/service.properties
catalog.routes.jms=jms/wanaku-jms-tool.camel.yaml
catalog.rules.jms=jms/wanaku-jms-tool.rules.yaml
catalog.services=jms
