/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.2-SNAPSHOT
 */
import type { Service } from "./service";

export type GetApiV1ManagementTargetsResourcesList200 = {
  [key: string]: Service;
};
