/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.6-SNAPSHOT
 */
import type { WanakuError } from "./wanakuError";
import type { WanakuResponseMapStringListServiceStateData } from "./wanakuResponseMapStringListServiceStateData";

export interface WanakuResponseMapStringListServiceState {
  error?: WanakuError;
  data?: WanakuResponseMapStringListServiceStateData;
}
