catalog.dependencies.aws-s3=aws-s3/aws-s3.dependencies.txt
catalog.description=Read objects from AWS S3 buckets
catalog.name=aws-s3-resource
catalog.routes.aws-s3=aws-s3/aws-s3.camel.yaml
catalog.rules.aws-s3=aws-s3/aws-s3.rules.yaml
catalog.services=aws-s3
catalog.properties.aws-s3=aws-s3/service.properties
catalog.versions=versions.properties
