catalog.dependencies.aws-sqs=aws-sqs/aws-sqs.dependencies.txt
catalog.description=Send and receive correlated messages via AWS SQS
catalog.name=aws-sqs-tool
catalog.properties.aws-sqs=aws-sqs/service.properties
catalog.routes.aws-sqs=aws-sqs/aws-sqs.camel.yaml
catalog.rules.aws-sqs=aws-sqs/aws-sqs.rules.yaml
catalog.services=aws-sqs
