quarkus.http.host-enabled=true
quarkus.http.port=8081
quarkus.http.non-application-root-path=/q
quarkus.banner.enabled = false
quarkus.devservices.enabled = false
quarkus.console.enabled = false

quarkus.grpc.server.host=0.0.0.0
# If running multiple services on the same host, then you must pick an unique port
%dev.quarkus.grpc.server.port=9010
%test.quarkus.grpc.server.port=9010

quarkus.log.level=WARNING
quarkus.log.category."ai.wanaku".level=INFO
%dev.quarkus.log.category."ai.wanaku".level=DEBUG
%test.quarkus.log.category."ai.wanaku".level=INFO

wanaku.service.name=performancenoop
wanaku.service.base-uri=performancenoop://
wanaku.service.performance.delay=100

# Registration settings
#wanaku.service.registration.uri=http://localhost:8080
#wanaku.service.registration.interval=10s
#wanaku.service.registration.retry-wait-seconds=1
#wanaku.service.registration.retries=3
#wanaku.service.registration.delay-seconds=3

# Auth settings are inherited from wanaku-capabilities-base.
# Override auth.server, quarkus.oidc-client.client-id, or
# quarkus.oidc-client.credentials.secret here if needed.
