catalog.dependencies.azure-files=azure-files/azure-files.dependencies.txt
catalog.description=Read files from Azure Storage file shares
catalog.name=azure-files-resource
catalog.properties.azure-files=azure-files/service.properties
catalog.routes.azure-files=azure-files/azure-files.camel.yaml
catalog.rules.azure-files=azure-files/azure-files.rules.yaml
catalog.services=azure-files
catalog.versions=versions.properties
