catalog.dependencies.telegram-sink=telegram-sink/telegram-sink.dependencies.txt
catalog.description=Send messages via Telegram Bot
catalog.name=telegram-sink-tool
catalog.routes.telegram-sink=telegram-sink/telegram-sink.camel.yaml
catalog.rules.telegram-sink=telegram-sink/telegram-sink.rules.yaml
catalog.services=telegram-sink
