%dev.quarkus.infinispan-client.hosts=localhost:11222
%dev.quarkus.infinispan-client.username=admin
%dev.quarkus.infinispan-client.password=secret

# Cache creation is now programmatic
# quarkus.infinispan-client.cache.tool.configuration-resource=
# quarkus.infinispan-client.cache.prompt.configuration-resource=
# quarkus.infinispan-client.cache.resource.configuration-resource=
# quarkus.infinispan-client.cache.datastore.configuration-resource=
# quarkus.infinispan-client.cache.namespace.configuration-resource=
# quarkus.infinispan-client.cache.forward.configuration-resource=
