%dev.quarkus.infinispan-client.hosts=localhost:11222
%dev.quarkus.infinispan-client.username=admin
%dev.quarkus.infinispan-client.password=secret

quarkus.infinispan-client.cache.tool.configuration-resource=config/indexed-cache.json
quarkus.infinispan-client.cache.prompt.configuration-resource=config/indexed-cache.json
quarkus.infinispan-client.cache.resource.configuration-resource=config/indexed-cache.json
quarkus.infinispan-client.cache.datastore.configuration-resource=config/indexed-cache.json
quarkus.infinispan-client.cache.namespace.configuration-resource=config/indexed-cache.json
quarkus.infinispan-client.cache.forward.configuration-resource=config/indexed-cache.json
