tool.description=Vectorized search in Pinecone using camel-pinecone
pinecone.token={{pinecone.token}}
pinecone.index.name={{pinecone.index.name}}
pinecone.index.host={{pinecone.index.host}}
pinecone.cloud={{pinecone.cloud}}
pinecone.cloud.region={{pinecone.cloud.region}}
pinecone.collection={{pinecone.collection}}
pinecone.top.k=5
