catalog.dependencies.pinecone-search=pinecone-search/pinecone-search.dependencies.txt
catalog.description=Vectorized search in Pinecone using camel-pinecone
catalog.name=camel-pinecone-tool
catalog.properties.pinecone-search=pinecone-search/service.properties
catalog.routes.pinecone-search=pinecone-search/pinecone-search.camel.yaml
catalog.rules.pinecone-search=pinecone-search/pinecone-search.rules.yaml
catalog.services=pinecone-search
