catalog.dependencies.mail-sink=mail-sink/mail-sink.dependencies.txt
catalog.description=Send emails via SMTP
catalog.name=mail-sink-tool
catalog.routes.mail-sink=mail-sink/mail-sink.camel.yaml
catalog.rules.mail-sink=mail-sink/mail-sink.rules.yaml
catalog.services=mail-sink
catalog.versions=versions.properties
