catalog.dependencies.github-pr-comments=github-pr-comments/github-pr-comments.dependencies.txt
catalog.description=Fetch comments from GitHub Pull Requests
catalog.name=github-pr-comments-tool
catalog.properties.github-pr-comments=github-pr-comments/service.properties
catalog.routes.github-pr-comments=github-pr-comments/github-pr-comments.camel.yaml
catalog.rules.github-pr-comments=github-pr-comments/github-pr-comments.rules.yaml
catalog.services=github-pr-comments
