package ai.wanaku.operator.util;

public final class EnvironmentVariables {
    public static final String DEFAULT_AUTH_REALM = "wanaku";
    public static final String AUTH_SERVER = "AUTH_SERVER";
    public static final String AUTH_PROXY = "AUTH_PROXY";
    public static final String AUTH_REALM = "AUTH_REALM";
    public static final String QUARKUS_MCP_SERVER_TRAFFIC_LOGGING_ENABLED =
            "QUARKUS_MCP_SERVER_TRAFFIC_LOGGING_ENABLED";
    public static final String WANAKU_SERVICE_REGISTRATION_URI = "WANAKU_SERVICE_REGISTRATION_URI";
    public static final String QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET = "QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET";

    public static final String CAMEL_INTEGRATION_CAPABILITY_REGISTRATION_URL = "REGISTRATION_URL";
    public static final String CAMEL_INTEGRATION_CAPABILITY_REGISTRATION_ANNOUNCE_ADDRESS =
            "REGISTRATION_ANNOUNCE_ADDRESS";
    public static final String CAMEL_INTEGRATION_CAPABILITY_GRPC_PORT = "GRPC_PORT";
    public static final String CAMEL_INTEGRATION_CAPABILITY_SERVICE_NAME = "SERVICE_NAME";
    public static final String CAMEL_INTEGRATION_CAPABILITY_ROUTES_PATH = "ROUTES_PATH";
    public static final String CAMEL_INTEGRATION_CAPABILITY_ROUTES_RULES = "ROUTES_RULES";
    public static final String CAMEL_INTEGRATION_CAPABILITY_SERVICE_CATALOG = "SERVICE_CATALOG";
    public static final String CAMEL_INTEGRATION_CAPABILITY_SERVICE_CATALOG_SYSTEM = "SERVICE_CATALOG_SYSTEM";
    public static final String CAMEL_INTEGRATION_CAPABILITY_TOKEN_ENDPOINT = "TOKEN_ENDPOINT";
    public static final String CAMEL_INTEGRATION_CAPABILITY_CLIENT_ID = "CLIENT_ID";
    public static final String CAMEL_INTEGRATION_CAPABILITY_CLIENT_SECRET = "CLIENT_SECRET";

    public static final String CAMEL_CODE_EXECUTION_ENGINE_SERVICE_NAME = "SERVICE_NAME";
    public static final String CAMEL_CODE_EXECUTION_ENGINE_DEPLOYMENT_MODE = "DEPLOYMENT_MODE";
    public static final String CAMEL_CODE_EXECUTION_ENGINE_ENGINE_TYPE = "ENGINE_TYPE";
    public static final String CAMEL_CODE_EXECUTION_ENGINE_LANGUAGE_NAME = "LANGUAGE_NAME";
    public static final String CAMEL_CODE_EXECUTION_ENGINE_GRPC_PORT = "GRPC_PORT";
    public static final String CAMEL_CODE_EXECUTION_ENGINE_COMPONENT_ALLOWLIST = "COMPONENT_ALLOWLIST";
    public static final String CAMEL_CODE_EXECUTION_ENGINE_COMPONENT_BLOCKLIST = "COMPONENT_BLOCKLIST";
    public static final String CAMEL_CODE_EXECUTION_ENGINE_ENDPOINT_ALLOWLIST = "ENDPOINT_ALLOWLIST";
    public static final String CAMEL_CODE_EXECUTION_ENGINE_ENDPOINT_BLOCKLIST = "ENDPOINT_BLOCKLIST";
    public static final String CAMEL_CODE_EXECUTION_ENGINE_ROUTE_ALLOWLIST = "ROUTE_ALLOWLIST";
    public static final String CAMEL_CODE_EXECUTION_ENGINE_ROUTE_BLOCKLIST = "ROUTE_BLOCKLIST";
    public static final String CAMEL_CODE_EXECUTION_ENGINE_DEPENDENCY_CACHE_STRATEGY = "CACHE_STRATEGY";
    public static final String CAMEL_CODE_EXECUTION_ENGINE_DEPENDENCY_CACHE_NAME = "CACHE_NAME";
    public static final String CAMEL_CODE_EXECUTION_ENGINE_DEPENDENCY_CACHE_TEMPLATE_NAMESPACE =
            "CACHE_TEMPLATE_NAMESPACE";
    public static final String CAMEL_CODE_EXECUTION_ENGINE_DEPENDENCY_CACHE_TEMPLATE_PREFIX = "CACHE_TEMPLATE_PREFIX";
    public static final String CAMEL_CODE_EXECUTION_ENGINE_REMOTE_HOST = "REMOTE_HOST";
    public static final String CAMEL_CODE_EXECUTION_ENGINE_REMOTE_PORT = "REMOTE_PORT";
    public static final String CAMEL_CODE_EXECUTION_ENGINE_REMOTE_SCHEME = "REMOTE_SCHEME";
    public static final String CAMEL_CODE_EXECUTION_ENGINE_REMOTE_PATH = "REMOTE_PATH";

    private EnvironmentVariables() {}
}
