#!/bin/sh

localDir="$(dirname "$0")"

if [ -x "${localDir}/wanaku-cli" ]; then
    exec "${localDir}/wanaku-cli" "$@"
fi

installDir="$(dirname "${localDir}")"
exec java --add-opens=java.base/java.lang=ALL-UNNAMED -jar "${installDir}"/quarkus-run.jar "$@"