#!/bin/sh

localDir="$(dirname "$0")"

if [ -x "${localDir}/wanaku-cli" ]; then
    exec "${localDir}/wanaku-cli" "$@"
fi

installDir="$(dirname "${localDir}")"
java -jar "${installDir}"/quarkus-run.jar "$@"