catalog.dependencies.sftp=sftp/sftp.dependencies.txt
catalog.description=Read files from SFTP servers
catalog.name=sftp-resource
catalog.properties.sftp=sftp/service.properties
catalog.routes.sftp=sftp/sftp.camel.yaml
catalog.rules.sftp=sftp/sftp.rules.yaml
catalog.services=sftp
catalog.versions=versions.properties
