catalog.dependencies.echo=echo/echo.dependencies.txt
catalog.description=Echo back the input message duplicated with a configurable separator
catalog.name=echo-tool
catalog.properties.echo=echo/service.properties
catalog.routes.echo=echo/wanaku-echo-tool.camel.yaml
catalog.rules.echo=echo/wanaku-echo-tool.rules.yaml
catalog.services=echo
