/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.2-SNAPSHOT
 */

export type DeleteApiV1ServiceTemplateRemoveParams = {
  name?: string;
};
