/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { SystemInstruction } from './systemInstruction';
import type { PlaceholderDefinition } from './placeholderDefinition';

export interface DeploymentInstructions {
  catalogName?: string;
  catalogType?: string;
  deploymentModel?: string;
  systems?: SystemInstruction[];
  placeholders?: PlaceholderDefinition[];
}
