/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.1-SNAPSHOT
 */

export interface ForwardReference {
  id?: string;
  name?: string;
  address?: string;
  namespace?: string;
}
