/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { ForwardRequestRoots } from './forwardRequestRoots';

export interface ForwardRequest {
  name?: string;
  address?: string;
  namespace?: string;
  roots?: ForwardRequestRoots;
}
