/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.2.0
 */
import type { InputSchemaProperties } from "./inputSchemaProperties";

export interface InputSchema {
  type?: string;
  properties?: InputSchemaProperties;
  required?: string[];
}
