/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0
 */
import type { Property } from "./property";

export type InputSchemaProperties = { [key: string]: Property };
