/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.2.0
 */
import type { MediaTypeParameters } from "./mediaTypeParameters";

export interface MediaType {
  type?: string;
  subtype?: string;
  parameters?: MediaTypeParameters;
  hash?: number;
  wildcardType?: boolean;
  wildcardSubtype?: boolean;
}
