/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.3-SNAPSHOT
 */

export interface PlaceholderDefinition {
  key?: string;
  label?: string;
  description?: string;
  defaultValue?: string;
  type?: string;
}
