/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0
 */
import type { PromptReference } from "./promptReference";

export interface PromptPayload {
  promptReference?: PromptReference;
  configurationData?: string;
  secretsData?: string;
  payload?: PromptReference;
}
