/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.2.0-SNAPSHOT
 */
import type { ResourceReferenceLabels } from "./resourceReferenceLabels";
import type { Param } from "./param";

export interface ResourceReference {
  labels?: ResourceReferenceLabels;
  id?: string;
  location?: string;
  type?: string;
  name?: string;
  description?: string;
  mimeType?: string;
  params?: Param[];
  configurationURI?: string;
  secretsURI?: string;
  namespace?: string;
}
