/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */
import type { ResourceReference } from "./resourceReference";

export interface ResourcePayload {
  resourceReference?: ResourceReference;
  configurationData?: string;
  secretsData?: string;
  payload?: ResourceReference;
}
