/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */

export type ServiceType = (typeof ServiceType)[keyof typeof ServiceType];

export const ServiceType = {
  RESOURCE_PROVIDER: "RESOURCE_PROVIDER",
  TOOL_INVOKER: "TOOL_INVOKER",
  MULTI_CAPABILITY: "MULTI_CAPABILITY",
} as const;
