/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.2.0
 */
import type { Instant } from "./instant";

export interface StaleCapabilityInfo {
  id?: string;
  serviceName?: string;
  serviceType?: string;
  host?: string;
  port?: number;
  healthStatus?: string;
  lastSeen?: Instant;
}
