/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { TemplateInstantiationRequestProperties } from './templateInstantiationRequestProperties';

export interface TemplateInstantiationRequest {
  templateName?: string;
  properties?: TemplateInstantiationRequestProperties;
  serviceName?: string;
  serviceSystem?: string;
}
