/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.2.0
 */

export interface ToolCallRecord {
  id?: string;
  eventId?: string;
  eventType?: string;
  timestamp?: number;
  toolName?: string;
  toolType?: string;
  connectionId?: string;
  serviceId?: string;
  serviceAddress?: string;
  error?: boolean;
  duration?: number;
  errorCategory?: string;
  errorMessage?: string;
  argumentKeys?: string;
}
