/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0
 */
import type { WanakuError } from "./wanakuError";
import type { ForwardReference } from "./forwardReference";

export interface WanakuResponseForwardReference {
  error?: WanakuError;
  data?: ForwardReference;
}
