/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.2.0
 */
import type { WanakuError } from "./wanakuError";
import type { DeploymentInstructions } from "./deploymentInstructions";

export interface WanakuResponseDeploymentInstructions {
  error?: WanakuError;
  data?: DeploymentInstructions;
}
