/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.2.0-SNAPSHOT
 */
import type { WanakuError } from "./wanakuError";
import type { ServiceTarget } from "./serviceTarget";

export interface WanakuResponseListServiceTarget {
  error?: WanakuError;
  data?: ServiceTarget[];
}
