/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.2.0-SNAPSHOT
 */

export type WanakuResponseListMapStringStringDataItem = {
  [key: string]: string;
};
