/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.1-SNAPSHOT
 */
import type { WanakuError } from "./wanakuError";
import type { ForwardReference } from "./forwardReference";

export interface WanakuResponseListForwardReference {
  error?: WanakuError;
  data?: ForwardReference[];
}
