/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { WanakuError } from "./wanakuError";
import type { ToolCallRecord } from "./toolCallRecord";

export interface WanakuResponseToolCallRecord {
  error?: WanakuError;
  data?: ToolCallRecord;
}
