catalog.dependencies.github-pullrequest-source=github-pullrequest-source/github-pullrequest-source.dependencies.txt
catalog.description=Fetch pull request information from GitHub
catalog.name=github-pullrequest-source-tool
catalog.routes.github-pullrequest-source=github-pullrequest-source/github-pullrequest-source.camel.yaml
catalog.rules.github-pullrequest-source=github-pullrequest-source/github-pullrequest-source.rules.yaml
catalog.services=github-pullrequest-source
catalog.versions=versions.properties
