catalog.dependencies.watson-nlu-sink=watson-nlu-sink/watson-nlu-sink.dependencies.txt
catalog.description=Analyze text using IBM Watson Natural Language Understanding
catalog.name=watson-nlu-sink-tool
catalog.properties.watson-nlu-sink=watson-nlu-sink/service.properties
catalog.routes.watson-nlu-sink=watson-nlu-sink/watson-nlu-sink.camel.yaml
catalog.rules.watson-nlu-sink=watson-nlu-sink/watson-nlu-sink.rules.yaml
catalog.services=watson-nlu-sink
catalog.versions=versions.properties
