tool.description=Send a message to RabbitMQ
rabbitmq.exchange=my-exchange
rabbitmq.routing.key=my-key
rabbitmq.queue=my-queue
forage.spring.rabbitmq.host=localhost
forage.spring.rabbitmq.port=5672
forage.spring.rabbitmq.username=admin
forage.spring.rabbitmq.password=password