apiVersion: "wanaku.ai/v1alpha1"
kind: Wanaku
metadata:
  name: wanaku-dev
spec:
  auth:
# This is the address of the authorization server (in the format: http://address)
    authServer: ""
# Address of the proxy (in the format: http://address). It could be the same as the auth server - default) or "auto" (for using
# Wanaku as the proxy via OIDC proxy.
#    authProxy: ""
  secrets:
# This is the OIDC credentials secret for the services
    oidcCredentialsSecret: ""
# Global image pull policy for all deployments (router and capabilities)
# Valid values: Always, IfNotPresent, Never
# Default: IfNotPresent
# Can be overridden per-component using router.imagePullPolicy or capability.imagePullPolicy
#  imagePullPolicy: IfNotPresent
# Ingress configuration for Kubernetes clusters (not needed for OpenShift)
# OpenShift clusters auto-generate the host via Routes, but Kubernetes requires explicit configuration
# Uncomment and set the host when deploying on vanilla Kubernetes:
#  ingress:
#    host: wanaku.example.com
# Router settings are optional
  router:
    env:
# It is possible to set environment variables for the router by adding a map like the one below
#      - name: ENVIRONMENT_VARIABLE_1
#        value: value1
#      - name: ENVIRONMENT_VARIABLE_2
#        value: value2
# You can also set a custom image for the router
#    image: quay.io/wanaku/wanaku-router-backend:latest # Optional
# Override pull policy for router only (takes precedence over global setting)
#    imagePullPolicy: Always
  capabilities:
# For the capabilities, you need to provide the name, image to use and any environment variables required:
# You can also optionally set imagePullPolicy per capability (overrides global setting)
    - name: wanaku-http
      image: quay.io/wanaku/wanaku-tool-service-http:latest
#      imagePullPolicy: Always  # Optional: Always, IfNotPresent, Never
    - name: finance-system
      image: quay.io/wanaku/camel-integration-capability:latest
    - name: employee-system
      type: camel-integration-capability
      image: quay.io/wanaku/camel-integration-capability:latest
      # When using a camel integration capability, must always set the path to the routes file and to the rules file
      env:
        # The path to the routes file, should be within /data (i.e.: /data/my-system.camel.yaml)
        - name: ROUTES_PATH
          value: ""
        # The path to the rules file, should be within /data (i.e.: /data/my-system-rules.yaml)
        - name: ROUTES_RULES
          value: ""
        # Note, you can use oc cp file <pod name>:/data/<file> to copy the files