catalog.dependencies.rabbitmq=rabbitmq/rabbitmq.dependencies.txt
catalog.description=Send and receive messages to and from RabbitMQ
catalog.name=rabbitmq-tool
catalog.routes.rabbitmq=rabbitmq/rabbitmq.camel.yaml
catalog.rules.rabbitmq=rabbitmq/rabbitmq.rules.yaml
catalog.services=rabbitmq
catalog.versions=versions.properties
