/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type {
  ForwardEntry,
  Interaction,
  MetricsSnapshot,
  NamespaceEntry,
  PromptEntry,
  ResourceEntry,
  ToolEntry,
} from "../models";

import { customFetch } from "../custom-fetch";
export type listForwardsResponse200 = {
  data: ForwardEntry[];
  status: 200;
};

export type listForwardsResponseSuccess = listForwardsResponse200 & {
  headers: Headers;
};
export type listForwardsResponse = listForwardsResponseSuccess;

export const getListForwardsUrl = () => {
  return `/api/v1/forwards`;
};

export const listForwards = async (
  options?: RequestInit,
): Promise<listForwardsResponse> => {
  return customFetch<listForwardsResponse>(getListForwardsUrl(), {
    ...options,
    method: "GET",
  });
};

export type createForwardResponse200 = {
  data: unknown;
  status: 200;
};

export type createForwardResponseSuccess = createForwardResponse200 & {
  headers: Headers;
};
export type createForwardResponse = createForwardResponseSuccess;

export const getCreateForwardUrl = () => {
  return `/api/v1/forwards`;
};

export const createForward = async (
  forwardEntry: ForwardEntry,
  options?: RequestInit,
): Promise<createForwardResponse> => {
  return customFetch<createForwardResponse>(getCreateForwardUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(forwardEntry),
  });
};

export type getForwardResponse200 = {
  data: ForwardEntry;
  status: 200;
};

export type getForwardResponse404 = {
  data: void;
  status: 404;
};

export type getForwardResponseSuccess = getForwardResponse200 & {
  headers: Headers;
};
export type getForwardResponseError = getForwardResponse404 & {
  headers: Headers;
};

export type getForwardResponse =
  | getForwardResponseSuccess
  | getForwardResponseError;

export const getGetForwardUrl = (name: string) => {
  return `/api/v1/forwards/${name}`;
};

export const getForward = async (
  name: string,
  options?: RequestInit,
): Promise<getForwardResponse> => {
  return customFetch<getForwardResponse>(getGetForwardUrl(name), {
    ...options,
    method: "GET",
  });
};

export type deleteForwardResponse200 = {
  data: void;
  status: 200;
};

export type deleteForwardResponse404 = {
  data: void;
  status: 404;
};

export type deleteForwardResponseSuccess = deleteForwardResponse200 & {
  headers: Headers;
};
export type deleteForwardResponseError = deleteForwardResponse404 & {
  headers: Headers;
};

export type deleteForwardResponse =
  | deleteForwardResponseSuccess
  | deleteForwardResponseError;

export const getDeleteForwardUrl = (name: string) => {
  return `/api/v1/forwards/${name}`;
};

export const deleteForward = async (
  name: string,
  options?: RequestInit,
): Promise<deleteForwardResponse> => {
  return customFetch<deleteForwardResponse>(getDeleteForwardUrl(name), {
    ...options,
    method: "DELETE",
  });
};

export type refreshForwardResponse200 = {
  data: unknown;
  status: 200;
};

export type refreshForwardResponse404 = {
  data: void;
  status: 404;
};

export type refreshForwardResponseSuccess = refreshForwardResponse200 & {
  headers: Headers;
};
export type refreshForwardResponseError = refreshForwardResponse404 & {
  headers: Headers;
};

export type refreshForwardResponse =
  | refreshForwardResponseSuccess
  | refreshForwardResponseError;

export const getRefreshForwardUrl = (name: string) => {
  return `/api/v1/forwards/${name}/refreshes`;
};

export const refreshForward = async (
  name: string,
  options?: RequestInit,
): Promise<refreshForwardResponse> => {
  return customFetch<refreshForwardResponse>(getRefreshForwardUrl(name), {
    ...options,
    method: "POST",
  });
};

export type listInteractionsResponse200 = {
  data: Interaction[];
  status: 200;
};

export type listInteractionsResponseSuccess = listInteractionsResponse200 & {
  headers: Headers;
};
export type listInteractionsResponse = listInteractionsResponseSuccess;

export const getListInteractionsUrl = () => {
  return `/api/v1/interactions`;
};

export const listInteractions = async (
  options?: RequestInit,
): Promise<listInteractionsResponse> => {
  return customFetch<listInteractionsResponse>(getListInteractionsUrl(), {
    ...options,
    method: "GET",
  });
};

export type clearInteractionsResponse200 = {
  data: void;
  status: 200;
};

export type clearInteractionsResponseSuccess = clearInteractionsResponse200 & {
  headers: Headers;
};
export type clearInteractionsResponse = clearInteractionsResponseSuccess;

export const getClearInteractionsUrl = () => {
  return `/api/v1/interactions`;
};

export const clearInteractions = async (
  options?: RequestInit,
): Promise<clearInteractionsResponse> => {
  return customFetch<clearInteractionsResponse>(getClearInteractionsUrl(), {
    ...options,
    method: "DELETE",
  });
};

export type getStatisticsResponse200 = {
  data: unknown;
  status: 200;
};

export type getStatisticsResponseSuccess = getStatisticsResponse200 & {
  headers: Headers;
};
export type getStatisticsResponse = getStatisticsResponseSuccess;

export const getGetStatisticsUrl = () => {
  return `/api/v1/management/statistics`;
};

export const getStatistics = async (
  options?: RequestInit,
): Promise<getStatisticsResponse> => {
  return customFetch<getStatisticsResponse>(getGetStatisticsUrl(), {
    ...options,
    method: "GET",
  });
};

export type getMetricsResponse200 = {
  data: MetricsSnapshot;
  status: 200;
};

export type getMetricsResponseSuccess = getMetricsResponse200 & {
  headers: Headers;
};
export type getMetricsResponse = getMetricsResponseSuccess;

export const getGetMetricsUrl = () => {
  return `/api/v1/metrics`;
};

export const getMetrics = async (
  options?: RequestInit,
): Promise<getMetricsResponse> => {
  return customFetch<getMetricsResponse>(getGetMetricsUrl(), {
    ...options,
    method: "GET",
  });
};

export type listNamespacesResponse200 = {
  data: NamespaceEntry[];
  status: 200;
};

export type listNamespacesResponseSuccess = listNamespacesResponse200 & {
  headers: Headers;
};
export type listNamespacesResponse = listNamespacesResponseSuccess;

export const getListNamespacesUrl = () => {
  return `/api/v1/namespaces`;
};

export const listNamespaces = async (
  options?: RequestInit,
): Promise<listNamespacesResponse> => {
  return customFetch<listNamespacesResponse>(getListNamespacesUrl(), {
    ...options,
    method: "GET",
  });
};

export type createNamespaceResponse200 = {
  data: NamespaceEntry;
  status: 200;
};

export type createNamespaceResponseSuccess = createNamespaceResponse200 & {
  headers: Headers;
};
export type createNamespaceResponse = createNamespaceResponseSuccess;

export const getCreateNamespaceUrl = () => {
  return `/api/v1/namespaces`;
};

export const createNamespace = async (
  namespaceEntry: NamespaceEntry,
  options?: RequestInit,
): Promise<createNamespaceResponse> => {
  return customFetch<createNamespaceResponse>(getCreateNamespaceUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(namespaceEntry),
  });
};

export type getNamespaceResponse200 = {
  data: NamespaceEntry;
  status: 200;
};

export type getNamespaceResponse404 = {
  data: void;
  status: 404;
};

export type getNamespaceResponseSuccess = getNamespaceResponse200 & {
  headers: Headers;
};
export type getNamespaceResponseError = getNamespaceResponse404 & {
  headers: Headers;
};

export type getNamespaceResponse =
  | getNamespaceResponseSuccess
  | getNamespaceResponseError;

export const getGetNamespaceUrl = (name: string) => {
  return `/api/v1/namespaces/${name}`;
};

export const getNamespace = async (
  name: string,
  options?: RequestInit,
): Promise<getNamespaceResponse> => {
  return customFetch<getNamespaceResponse>(getGetNamespaceUrl(name), {
    ...options,
    method: "GET",
  });
};

export type deleteNamespaceResponse200 = {
  data: void;
  status: 200;
};

export type deleteNamespaceResponse404 = {
  data: void;
  status: 404;
};

export type deleteNamespaceResponseSuccess = deleteNamespaceResponse200 & {
  headers: Headers;
};
export type deleteNamespaceResponseError = deleteNamespaceResponse404 & {
  headers: Headers;
};

export type deleteNamespaceResponse =
  | deleteNamespaceResponseSuccess
  | deleteNamespaceResponseError;

export const getDeleteNamespaceUrl = (name: string) => {
  return `/api/v1/namespaces/${name}`;
};

export const deleteNamespace = async (
  name: string,
  options?: RequestInit,
): Promise<deleteNamespaceResponse> => {
  return customFetch<deleteNamespaceResponse>(getDeleteNamespaceUrl(name), {
    ...options,
    method: "DELETE",
  });
};

export type listPromptsResponse200 = {
  data: PromptEntry[];
  status: 200;
};

export type listPromptsResponseSuccess = listPromptsResponse200 & {
  headers: Headers;
};
export type listPromptsResponse = listPromptsResponseSuccess;

export const getListPromptsUrl = () => {
  return `/api/v1/prompts`;
};

export const listPrompts = async (
  options?: RequestInit,
): Promise<listPromptsResponse> => {
  return customFetch<listPromptsResponse>(getListPromptsUrl(), {
    ...options,
    method: "GET",
  });
};

export type getPromptResponse200 = {
  data: PromptEntry;
  status: 200;
};

export type getPromptResponse404 = {
  data: void;
  status: 404;
};

export type getPromptResponseSuccess = getPromptResponse200 & {
  headers: Headers;
};
export type getPromptResponseError = getPromptResponse404 & {
  headers: Headers;
};

export type getPromptResponse =
  | getPromptResponseSuccess
  | getPromptResponseError;

export const getGetPromptUrl = (name: string) => {
  return `/api/v1/prompts/${name}`;
};

export const getPrompt = async (
  name: string,
  options?: RequestInit,
): Promise<getPromptResponse> => {
  return customFetch<getPromptResponse>(getGetPromptUrl(name), {
    ...options,
    method: "GET",
  });
};

export type deletePromptResponse200 = {
  data: void;
  status: 200;
};

export type deletePromptResponse404 = {
  data: void;
  status: 404;
};

export type deletePromptResponseSuccess = deletePromptResponse200 & {
  headers: Headers;
};
export type deletePromptResponseError = deletePromptResponse404 & {
  headers: Headers;
};

export type deletePromptResponse =
  | deletePromptResponseSuccess
  | deletePromptResponseError;

export const getDeletePromptUrl = (name: string) => {
  return `/api/v1/prompts/${name}`;
};

export const deletePrompt = async (
  name: string,
  options?: RequestInit,
): Promise<deletePromptResponse> => {
  return customFetch<deletePromptResponse>(getDeletePromptUrl(name), {
    ...options,
    method: "DELETE",
  });
};

export type listResourcesResponse200 = {
  data: ResourceEntry[];
  status: 200;
};

export type listResourcesResponseSuccess = listResourcesResponse200 & {
  headers: Headers;
};
export type listResourcesResponse = listResourcesResponseSuccess;

export const getListResourcesUrl = () => {
  return `/api/v1/resources`;
};

export const listResources = async (
  options?: RequestInit,
): Promise<listResourcesResponse> => {
  return customFetch<listResourcesResponse>(getListResourcesUrl(), {
    ...options,
    method: "GET",
  });
};

export type getResourceResponse200 = {
  data: ResourceEntry;
  status: 200;
};

export type getResourceResponse404 = {
  data: void;
  status: 404;
};

export type getResourceResponseSuccess = getResourceResponse200 & {
  headers: Headers;
};
export type getResourceResponseError = getResourceResponse404 & {
  headers: Headers;
};

export type getResourceResponse =
  | getResourceResponseSuccess
  | getResourceResponseError;

export const getGetResourceUrl = (name: string) => {
  return `/api/v1/resources/${name}`;
};

export const getResource = async (
  name: string,
  options?: RequestInit,
): Promise<getResourceResponse> => {
  return customFetch<getResourceResponse>(getGetResourceUrl(name), {
    ...options,
    method: "GET",
  });
};

export type deleteResourceResponse200 = {
  data: void;
  status: 200;
};

export type deleteResourceResponse404 = {
  data: void;
  status: 404;
};

export type deleteResourceResponseSuccess = deleteResourceResponse200 & {
  headers: Headers;
};
export type deleteResourceResponseError = deleteResourceResponse404 & {
  headers: Headers;
};

export type deleteResourceResponse =
  | deleteResourceResponseSuccess
  | deleteResourceResponseError;

export const getDeleteResourceUrl = (name: string) => {
  return `/api/v1/resources/${name}`;
};

export const deleteResource = async (
  name: string,
  options?: RequestInit,
): Promise<deleteResourceResponse> => {
  return customFetch<deleteResourceResponse>(getDeleteResourceUrl(name), {
    ...options,
    method: "DELETE",
  });
};

export type listToolsResponse200 = {
  data: ToolEntry[];
  status: 200;
};

export type listToolsResponseSuccess = listToolsResponse200 & {
  headers: Headers;
};
export type listToolsResponse = listToolsResponseSuccess;

export const getListToolsUrl = () => {
  return `/api/v1/tools`;
};

export const listTools = async (
  options?: RequestInit,
): Promise<listToolsResponse> => {
  return customFetch<listToolsResponse>(getListToolsUrl(), {
    ...options,
    method: "GET",
  });
};

export type getToolResponse200 = {
  data: ToolEntry;
  status: 200;
};

export type getToolResponse404 = {
  data: void;
  status: 404;
};

export type getToolResponseSuccess = getToolResponse200 & {
  headers: Headers;
};
export type getToolResponseError = getToolResponse404 & {
  headers: Headers;
};

export type getToolResponse = getToolResponseSuccess | getToolResponseError;

export const getGetToolUrl = (name: string) => {
  return `/api/v1/tools/${name}`;
};

export const getTool = async (
  name: string,
  options?: RequestInit,
): Promise<getToolResponse> => {
  return customFetch<getToolResponse>(getGetToolUrl(name), {
    ...options,
    method: "GET",
  });
};

export type deleteToolResponse200 = {
  data: void;
  status: 200;
};

export type deleteToolResponse404 = {
  data: void;
  status: 404;
};

export type deleteToolResponseSuccess = deleteToolResponse200 & {
  headers: Headers;
};
export type deleteToolResponseError = deleteToolResponse404 & {
  headers: Headers;
};

export type deleteToolResponse =
  | deleteToolResponseSuccess
  | deleteToolResponseError;

export const getDeleteToolUrl = (name: string) => {
  return `/api/v1/tools/${name}`;
};

export const deleteTool = async (
  name: string,
  options?: RequestInit,
): Promise<deleteToolResponse> => {
  return customFetch<deleteToolResponse>(getDeleteToolUrl(name), {
    ...options,
    method: "DELETE",
  });
};

export type healthzResponse200 = {
  data: unknown;
  status: 200;
};

export type healthzResponseSuccess = healthzResponse200 & {
  headers: Headers;
};
export type healthzResponse = healthzResponseSuccess;

export const getHealthzUrl = () => {
  return `/healthz`;
};

export const healthz = async (
  options?: RequestInit,
): Promise<healthzResponse> => {
  return customFetch<healthzResponse>(getHealthzUrl(), {
    ...options,
    method: "GET",
  });
};
