catalog.dependencies.ftp=ftp/ftp.dependencies.txt
catalog.description=Read files from FTP servers
catalog.name=ftp-resource
catalog.properties.ftp=ftp/service.properties
catalog.routes.ftp=ftp/ftp.camel.yaml
catalog.rules.ftp=ftp/ftp.rules.yaml
catalog.services=ftp
catalog.versions=versions.properties
