tool.description=Send a message to AWS SQS and wait for the correlated reply
aws.sqs.region={{aws.sqs.region}}
aws.sqs.accessKey={{aws.sqs.accessKey}}
aws.sqs.secretKey={{aws.sqs.secretKey}}
aws.sqs.request.queue={{aws.sqs.request.queue}}
aws.sqs.response.queue={{aws.sqs.response.queue}}
aws.sqs.reply.timeout-ms={{aws.sqs.reply.timeout-ms}}
