#Service Catalog Index - employee-system-v2
#Mon Apr 27 16:49:27 CEST 2026
catalog.dependencies.activemq6=activemq6/activemq6.dependencies.txt
catalog.description=Send and receives messages to and from ActiveMQ 6
catalog.name=activemq6-tool
catalog.routes.activemq6=activemq6/wanaku-activemq6-tool.camel.yaml
catalog.rules.activemq6=activemq6/wanaku-activemq6-tool.rules.yaml
catalog.services=activemq6
