tool.description=Send a message using JMS
request.queue=Some.Queue
response.queue=Some.Response.Queue
forage.jms.kind=artemis

# Broker connection URL
forage.jms.broker.url=tcp://localhost:61616

# Broker credentials
forage.jms.username=artemis
forage.jms.password=artemis
