---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.33.1
    app.quarkus.io/commit-id: 04304662a87a8c0e7dcbe028c99b3ae5577b5a13
    app.quarkus.io/vcs-uri: https://github.com/orpiske/wanaku.git
    app.quarkus.io/build-timestamp: 2026-05-01 - 07:57:00 +0000
  labels:
    app.kubernetes.io/name: wanaku-operator
    app.kubernetes.io/version: 0.1.1-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: wanaku-operator
  namespace: {{ .Release.Namespace }}
