---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.33.1
    app.quarkus.io/commit-id: f64602f29dab57bade54bc1f71e4dab0b9092cb8
    app.quarkus.io/vcs-uri: https://github.com/orpiske/wanaku.git
    app.quarkus.io/build-timestamp: 2026-04-28 - 13:48:02 +0000
  labels:
    app.kubernetes.io/name: wanaku-operator
    app.kubernetes.io/version: 0.1.1-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: wanaku-operator
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.app.ports.http }}
  selector:
    app.kubernetes.io/name: wanaku-operator
    app.kubernetes.io/version: 0.1.1-SNAPSHOT
  type: ClusterIP
