---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.27.2
    app.quarkus.io/commit-id: 90dc463f352476d0642c0803abf2056abc1af5b0
    app.quarkus.io/vcs-uri: https://github.com/orpiske/wanaku.git
    app.quarkus.io/build-timestamp: 2026-04-02 - 13:40:59 +0000
  labels:
    app.kubernetes.io/name: wanaku-operator
    app.kubernetes.io/version: 0.1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: wanaku-operator
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.app.ports.http }}
  selector:
    app.kubernetes.io/name: wanaku-operator
    app.kubernetes.io/version: 0.1.0-SNAPSHOT
  type: ClusterIP
