resource.description=Read files from SFTP servers
sftp.host={{sftp.host}}
sftp.port={{sftp.port}}
sftp.username={{sftp.username}}
sftp.authMethod=password
sftp.password={{sftp.password}}
sftp.privateKeyFile={{sftp.privateKeyFile}}
sftp.directory={{sftp.directory}}
sftp.knownHostsFile={{sftp.knownHostsFile}}
sftp.strictHostKeyChecking=true
sftp.disconnect=true
sftp.soTimeout=10000
sftp.timeout=30000
