[package]
name = "assembly-filter-action"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.41"
wit-bindgen-rt = "0.41"
serde_json = "1.0"

[package.metadata.component]
package = "wanaku:assembly-filter"

[package.metadata.component.target]
path = "wit/evaluator.wit"
world = "evaluator-action"
