catalog.dependencies.sql=sql/sql.dependencies.txt
catalog.description=Execute SQL queries against a relational database using Apache Camel SQL component
catalog.name=sql-tool
catalog.properties.sql=sql/service.properties
catalog.routes.sql=sql/sql.camel.yaml
catalog.rules.sql=sql/sql.rules.yaml
catalog.services=sql
