quarkus.qute.strict-rendering=false
quarkus.package.jar.type=mutable-jar

wanaku.http.auth=keycloak

quarkus.oidc-client.enabled=true

# Address of the Keycloak authentication server - adjust to your Keycloak instance
auth.server=${AUTH_SERVER:http://localhost:8543}
# Keycloak realm name - adjust to your Keycloak realm
auth.realm=${AUTH_REALM:wanaku}

# Address of the Keycloak authentication server
quarkus.oidc-client.auth-server-url=${auth.server}/realms/${auth.realm}

# Client identifier configured in Keycloak for capability services
quarkus.oidc-client.client-id=wanaku-service

# This forces the token to be renewed 1 minute before expiration
quarkus.oidc-client.refresh-token-time-skew=1m

# Client secret from Keycloak for service authentication - replace with your actual secret
quarkus.oidc-client.credentials.secret=<insert key here>

quarkus.log.level=WARNING
quarkus.log.category."ai.wanaku.core.capabilities".level=INFO
%dev.quarkus.log.category."ai.wanaku.core.capabilities".level=DEBUG
%test.quarkus.log.category."ai.wanaku.core.capabilities".level=INFO

# OpenTelemetry configuration
quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
quarkus.otel.exporter.otlp.traces.protocol=grpc
quarkus.otel.resource.attributes=service.name=${wanaku.service.name:wanaku-capability},service.version=${quarkus.application.version}
quarkus.otel.traces.sampler=parentbased_always_on
quarkus.otel.propagators=tracecontext,baggage

%local.quarkus.log.console.enabled=false
%local.quarkus.log.file.enabled=true
%local.quarkus.log.file.path=${user.home}/.wanaku/local/logs/${wanaku.service.name:wanaku-capability}.log
%local.quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] (%t) [traceId=%X{traceId}, requestId=%X{requestId}] %s%e%n
%local.quarkus.log.category."ai.wanaku".level=DEBUG

%test.quarkus.log.console.level=OFF
%test.quarkus.log.file.enabled=true
