catalog.dependencies.google-vertexai-sink=google-vertexai-sink/google-vertexai-sink.dependencies.txt
catalog.description=Generate content using Google Vertex AI
catalog.name=google-vertexai-sink-tool
catalog.properties.google-vertexai-sink=google-vertexai-sink/service.properties
catalog.routes.google-vertexai-sink=google-vertexai-sink/google-vertexai-sink.camel.yaml
catalog.rules.google-vertexai-sink=google-vertexai-sink/google-vertexai-sink.rules.yaml
catalog.services=google-vertexai-sink
catalog.versions=versions.properties
