/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.0.9
 */
import type { Instant } from "./instant";
import type { ServiceState } from "./serviceState";

export interface ActivityRecord {
  id?: string;
  lastSeen?: Instant;
  active?: boolean;
  states?: ServiceState[];
}
