/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */
import type { CodeExecutionErrorDetails } from "./codeExecutionErrorDetails";

export interface CodeExecutionError {
  error?: string;
  message?: string;
  taskId?: string;
  timestamp?: number;
  details?: CodeExecutionErrorDetails;
}
