/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */
import type { CodeExecutionRequestEnvironment } from "./codeExecutionRequestEnvironment";
import type { CodeExecutionRequestMetadata } from "./codeExecutionRequestMetadata";

export interface CodeExecutionRequest {
  code?: string;
  timeout?: number;
  environment?: CodeExecutionRequestEnvironment;
  arguments?: string[];
  metadata?: CodeExecutionRequestMetadata;
}
