/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */

export type CodeExecutionStatus =
  (typeof CodeExecutionStatus)[keyof typeof CodeExecutionStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CodeExecutionStatus = {
  PENDING: "PENDING",
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
  TIMEOUT: "TIMEOUT",
} as const;
