/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */
import type { CodeExecutionStatus } from "./codeExecutionStatus";

export interface CodeExecutionResponse {
  taskId?: string;
  streamUrl?: string;
  status?: CodeExecutionStatus;
  submittedAt?: number;
}
