/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.0.9
 */
import type { DataStoreLabels } from "./dataStoreLabels";

export interface DataStore {
  labels?: DataStoreLabels;
  id?: string;
  name?: string;
  data?: string;
}
