/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.6-SNAPSHOT
 */

export type EventType = (typeof EventType)[keyof typeof EventType];

 
export const EventType = {
  REGISTER: "REGISTER",
  DEREGISTER: "DEREGISTER",
  UPDATE: "UPDATE",
  PING: "PING",
} as const;
