/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */

export type HealthStatus = (typeof HealthStatus)[keyof typeof HealthStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthStatus = {
  PENDING: "PENDING",
  HEALTHY: "HEALTHY",
  UNHEALTHY: "UNHEALTHY",
  DOWN: "DOWN",
} as const;
