/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.0.9-SNAPSHOT
 */
import type { MediaTypeParameters } from "./mediaTypeParameters";

export interface MediaType {
  type?: string;
  subtype?: string;
  parameters?: MediaTypeParameters;
  hash?: number;
  wildcardType?: boolean;
  wildcardSubtype?: boolean;
}
