/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.0.9
 */
import type { NamespaceLabels } from "./namespaceLabels";

export interface Namespace {
  labels?: NamespaceLabels;
  id?: string;
  name?: string;
  path?: string;
}
