/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.0.9
 */

export interface Property {
  type?: string;
  description?: string;
  target?: string;
  scope?: string;
  value?: string;
}
