/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */
import type { ServiceType } from "./serviceType";

export interface ServiceTarget {
  id?: string;
  service?: string;
  host?: string;
  port?: number;
  serviceType?: ServiceType;
}
