/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */
import type { Instant } from "./instant";
import type { HealthStatus } from "./healthStatus";

export interface ServiceState {
  timestamp?: Instant;
  healthy?: boolean;
  healthStatus?: HealthStatus;
  reason?: string;
}
