/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */

export interface ServiceCatalogSummary {
  id?: string;
  name?: string;
  icon?: string;
  description?: string;
  services?: string[];
}
