/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.0.9
 */

export type ServiceType = (typeof ServiceType)[keyof typeof ServiceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceType = {
  RESOURCE_PROVIDER: "RESOURCE_PROVIDER",
  TOOL_INVOKER: "TOOL_INVOKER",
  MULTI_CAPABILITY: "MULTI_CAPABILITY",
} as const;
