/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */

export interface ServiceTarget {
  id?: string;
  serviceName?: string;
  host?: string;
  port?: number;
  serviceType?: string;
  serviceSubType?: string;
  languageName?: string;
  languageType?: string;
  languageSubType?: string;
}
