/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */
import type { ServiceCatalogSystem } from "./serviceCatalogSystem";

export interface ServiceCatalogDetail {
  id?: string;
  name?: string;
  icon?: string;
  description?: string;
  services?: ServiceCatalogSystem[];
}
