/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */
import type { Instant } from "./instant";

export interface StaleCapabilityInfo {
  id?: string;
  serviceName?: string;
  serviceType?: string;
  host?: string;
  port?: number;
  active?: boolean;
  lastSeen?: Instant;
}
