/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */
import type { CapabilityStatistics } from "./capabilityStatistics";

export interface SystemStatistics {
  toolsCount?: number;
  resourcesCount?: number;
  promptsCount?: number;
  forwardsCount?: number;
  dataStoresCount?: number;
  toolCapabilities?: CapabilityStatistics;
  resourceCapabilities?: CapabilityStatistics;
}
