/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */
import type { ToolReferenceLabels } from "./toolReferenceLabels";
import type { InputSchema } from "./inputSchema";

export interface ToolReference {
  labels?: ToolReferenceLabels;
  id?: string;
  name?: string;
  description?: string;
  uri?: string;
  type?: string;
  inputSchema?: InputSchema;
  namespace?: string;
  configurationURI?: string;
  secretsURI?: string;
}
