/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */
import type { WanakuError } from "./wanakuError";
import type { WanakuResponseMapStringListActivityRecordData } from "./wanakuResponseMapStringListActivityRecordData";

export interface WanakuResponseMapStringListActivityRecord {
  error?: WanakuError;
  data?: WanakuResponseMapStringListActivityRecordData;
}
