/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.0.9
 */
import type { ActivityRecord } from "./activityRecord";

export type WanakuResponseMapStringListActivityRecordData = {
  [key: string]: ActivityRecord[];
};
