/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.0.9
 */
import type { WanakuError } from "./wanakuError";
import type { Namespace } from "./namespace";

export interface WanakuResponseNamespace {
  error?: WanakuError;
  data?: Namespace;
}
