/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */
import type { WanakuError } from "./wanakuError";
import type { StaleCapabilityInfo } from "./staleCapabilityInfo";

export interface WanakuResponseListStaleCapabilityInfo {
  error?: WanakuError;
  data?: StaleCapabilityInfo[];
}
