/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */
import type { WanakuError } from "./wanakuError";
import type { WanakuResponseMapStringObjectData } from "./wanakuResponseMapStringObjectData";

export interface WanakuResponseMapStringObject {
  error?: WanakuError;
  data?: WanakuResponseMapStringObjectData;
}
