/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.0.9
 */
import type { WanakuError } from "./wanakuError";
import type { ToolReference } from "./toolReference";

export interface WanakuResponseListToolReference {
  error?: WanakuError;
  data?: ToolReference[];
}
