/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { ActionPolicy } from "./actionPolicy";
import type { RevisionMetadata } from "./revisionMetadata";

export interface ActionPolicyRevisionResponse {
  policy: ActionPolicy;
  revision: RevisionMetadata;
}
