/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export interface ActivateRevisionRequest {
  /**
   * @minimum 0
   * @nullable
   */
  expected_revision?: number | null;
}
