/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { Rule } from "./rule";

/**
 * A complete action-policy document.
 */
export interface ActionPolicy {
  rules?: Rule[];
}
