/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export type ActivationStatus =
  (typeof ActivationStatus)[keyof typeof ActivationStatus];

export const ActivationStatus = {
  active: "active",
  superseded: "superseded",
  rejected: "rejected",
} as const;
