/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * Controls whether audit mode invokes configured LLM evaluators.
 */
export type AuditLevel = (typeof AuditLevel)[keyof typeof AuditLevel];

export const AuditLevel = {
  basic: "basic",
  full: "full",
} as const;
