/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export type AuditDecision = (typeof AuditDecision)[keyof typeof AuditDecision];

export const AuditDecision = {
  allow: "allow",
  block: "block",
  warn: "warn",
  reject_malformed: "reject_malformed",
  error: "error",
} as const;
