/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export type AuditCategory = (typeof AuditCategory)[keyof typeof AuditCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuditCategory = {
  decision: "decision",
  administrative: "administrative",
} as const;
