/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { AuditEventActor } from "./auditEventActor";
import type { AuditEventAttributes } from "./auditEventAttributes";
import type { AuditEventAudience } from "./auditEventAudience";
import type { AuditCategory } from "./auditCategory";
import type { AuditEventConversationId } from "./auditEventConversationId";
import type { AuditDecision } from "./auditDecision";
import type { AuditEventDurationMs } from "./auditEventDurationMs";
import type { AuditEventEvaluator } from "./auditEventEvaluator";
import type { AuditEventFilter } from "./auditEventFilter";
import type { AuditEventNamespace } from "./auditEventNamespace";
import type { AuditEventPolicyRevision } from "./auditEventPolicyRevision";
import type { RedactionMetadata } from "./redactionMetadata";
import type { AuditEventRequestId } from "./auditEventRequestId";
import type { AuditEventResponseStatus } from "./auditEventResponseStatus";
import type { AuditEventTarget } from "./auditEventTarget";
import type { AuditEventTargetType } from "./auditEventTargetType";
import type { AuditEventUpstreamId } from "./auditEventUpstreamId";
import type { AuditEventWorkload } from "./auditEventWorkload";

export interface AuditEvent {
  actor?: AuditEventActor;
  attributes: AuditEventAttributes;
  audience?: AuditEventAudience;
  category: AuditCategory;
  conversation_id?: AuditEventConversationId;
  correlation_id: string;
  coverage_complete: boolean;
  decision: AuditDecision;
  /** @minimum 0 */
  dropped_events: number;
  /** @minimum 0 */
  duration_ms?: AuditEventDurationMs;
  evaluator?: AuditEventEvaluator;
  event_id: string;
  explanation: string;
  filter?: AuditEventFilter;
  namespace?: AuditEventNamespace;
  operation: string;
  payload?: unknown;
  policy_revision?: AuditEventPolicyRevision;
  protocol: string;
  reason_code: string;
  redaction: RedactionMetadata;
  request_id?: AuditEventRequestId;
  /** @minimum 0 */
  response_status?: AuditEventResponseStatus;
  schema_version: string;
  /** @minimum 0 */
  sequence: number;
  stream_id: string;
  target?: AuditEventTarget;
  target_type?: AuditEventTargetType;
  timestamp: string;
  upstream_id?: AuditEventUpstreamId;
  workload?: AuditEventWorkload;
}
