/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { AuditCategory } from "./auditCategory";
import type { AuditDecision } from "./auditDecision";
import type { AuditEventAttributes } from "./auditEventAttributes";
import type { RedactionMetadata } from "./redactionMetadata";

export interface AuditEvent {
  /** @nullable */
  actor?: string | null;
  attributes: AuditEventAttributes;
  /** @nullable */
  audience?: string | null;
  category: AuditCategory;
  /** @nullable */
  conversation_id?: string | null;
  correlation_id: string;
  coverage_complete: boolean;
  decision: AuditDecision;
  /** @minimum 0 */
  dropped_events: number;
  /**
   * @minimum 0
   * @nullable
   */
  duration_ms?: number | null;
  /** @nullable */
  evaluator?: string | null;
  event_id: string;
  explanation: string;
  /** @nullable */
  filter?: string | null;
  /** @nullable */
  namespace?: string | null;
  operation: string;
  payload?: unknown;
  /** @nullable */
  policy_revision?: string | null;
  protocol: string;
  reason_code: string;
  redaction: RedactionMetadata;
  /** @nullable */
  request_id?: string | null;
  /**
   * @minimum 0
   * @nullable
   */
  response_status?: number | null;
  schema_version: string;
  /** @minimum 0 */
  sequence: number;
  stream_id: string;
  /** @nullable */
  target?: string | null;
  /** @nullable */
  target_type?: string | null;
  timestamp: string;
  /** @nullable */
  upstream_id?: string | null;
  /** @nullable */
  workload?: string | null;
}
