/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export type BindEvaluatorNamespace200 = {
  conversation_id: string;
  namespace: string;
};
