/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * Optional restrictions that further constrain where a binding may be used.
 * An empty vector means "no restriction on this dimension".
 */
export interface BindingRestrictions {
  /** Governed item identifiers this binding may be used for. */
  governed_items?: string[];
  /** Authenticated identities this binding may be used for. */
  identities?: string[];
  /** Namespaces in which this binding may be used. */
  namespaces?: string[];
  /** MCP operations this binding may be used for. */
  operations?: string[];
}
