/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * Cache rules for a binding's resolved credentials.
 */
export interface CacheRules {
  /**
   * An explicit bounded maximum TTL, in seconds. When absent and the
   * resolver supplies no expiry metadata, results are not cached.
   * @minimum 0
   * @nullable
   */
  maxTtlSeconds?: number | null;
}
