/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * An explicit bounded maximum TTL, in seconds. When absent and the
resolver supplies no expiry metadata, results are not cached.
 * @minimum 0
 */
export type CacheRulesMaxTtlSeconds = number | null;
