/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * The purpose a credential is used for. Discovery and invocation are kept
distinct in policy checks, resolution context, audit events, and cache keys.
 */
export type CredentialPurpose =
  (typeof CredentialPurpose)[keyof typeof CredentialPurpose];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CredentialPurpose = {
  discovery: "discovery",
  invocation: "invocation",
} as const;
