/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { CredentialPurpose } from "./credentialPurpose";
import type { CacheRules } from "./cacheRules";
import type { InjectionMechanism } from "./injectionMechanism";
import type { NormalizedOrigin } from "./normalizedOrigin";
import type { BindingRestrictions } from "./bindingRestrictions";
import type { SecretRef } from "./secretRef";

/**
 * A credential binding: a top-level resource operationally owned by one forward.

The binding holds only **opaque** secret references. It never stores inline
secret values, and management APIs expose only its non-secret metadata.
 */
export interface CredentialBinding {
  /** The credential purposes this binding is allowed to serve. */
  allowedPurposes: CredentialPurpose[];
  /** Cache rules for resolved credentials. */
  cache?: CacheRules;
  /** The owning forward's stable identifier (the forward name). */
  forwardId: string;
  /** Stable, non-secret binding identifier. */
  id: string;
  /** The outbound injection mechanism. */
  mechanism: InjectionMechanism;
  /** The exact normalized upstream origin this binding may target. */
  origin: NormalizedOrigin;
  /** Optional additional restrictions. */
  restrictions?: BindingRestrictions;
  /**
   * Monotonic binding revision. Any change to the binding must bump this so
cached credentials for the old revision are never reused.
   * @minimum 0
   */
  revision?: number;
  /** One or more opaque secret references resolved just in time. */
  secretRefs: SecretRef[];
}
