/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export interface DecisionSnapshot {
  /** @minimum 0 */
  block: number;
  /** @minimum 0 */
  filter_tools: number;
  /** @minimum 0 */
  pass: number;
  /** @minimum 0 */
  reject_malformed: number;
  /** @minimum 0 */
  set_metadata: number;
  /** @minimum 0 */
  warn: number;
}
