/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export interface DurationSnapshot {
  avg_ms: number;
  /** @minimum 0 */
  count: number;
  total_ms: number;
}
