/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export type Effect = (typeof Effect)[keyof typeof Effect];

export const Effect = {
  allow: "allow",
  deny: "deny",
} as const;
