/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * Controls whether governance decisions affect traffic.
 */
export type EnforcementMode =
  (typeof EnforcementMode)[keyof typeof EnforcementMode];

export const EnforcementMode = {
  enforce: "enforce",
  audit: "audit",
  disabled: "disabled",
} as const;
