/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * Controls whether governance decisions affect traffic.
 */
export type EnforcementMode =
  (typeof EnforcementMode)[keyof typeof EnforcementMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnforcementMode = {
  enforce: "enforce",
  audit: "audit",
  disabled: "disabled",
} as const;
