/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { DurationSnapshot } from "./durationSnapshot";

export interface EngineSnapshot {
  duration: DurationSnapshot;
  /** @minimum 0 */
  llm_failure: number;
  /** @minimum 0 */
  llm_success: number;
  /** @minimum 0 */
  passthrough_failure: number;
  /** @minimum 0 */
  passthrough_success: number;
}
