/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * What to do when a WASM action fails.
 */
export type ErrorPolicy = (typeof ErrorPolicy)[keyof typeof ErrorPolicy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorPolicy = {
  continue: "continue",
  block: "block",
} as const;
