/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { DecisionSnapshot } from "./decisionSnapshot";
import type { DurationSnapshot } from "./durationSnapshot";
import type { EngineSnapshot } from "./engineSnapshot";
import type { LlmSnapshot } from "./llmSnapshot";
import type { SchemaSnapshot } from "./schemaSnapshot";
import type { WasmSnapshot } from "./wasmSnapshot";

export interface EvaluatorSnapshot {
  decisions: DecisionSnapshot;
  engine: EngineSnapshot;
  llm: LlmSnapshot;
  pipeline_duration: DurationSnapshot;
  schema: SchemaSnapshot;
  wasm: WasmSnapshot;
}
