/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { EvaluationEngineOneOfFourType } from "./evaluationEngineOneOfFourType";

/**
 * Pass the normalized MCP context directly to the processor.
 */
export type EvaluationEngineOneOfFour = {
  type: EvaluationEngineOneOfFourType;
};
