/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { SystemOneDef } from "./systemOneDef";
import type { EvaluationEngineOneOfFourAllOf } from "./evaluationEngineOneOfFourAllOf";

/**
 * TypeSafe System One typed evaluation.
 */
export type EvaluationEngineOneOfFour = SystemOneDef &
  EvaluationEngineOneOfFourAllOf;
