/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export type EvaluationEngineOneOfFourAllOfType =
  (typeof EvaluationEngineOneOfFourAllOfType)[keyof typeof EvaluationEngineOneOfFourAllOfType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EvaluationEngineOneOfFourAllOfType = {
  "typesafe-system-one": "typesafe-system-one",
} as const;
