/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export type EvaluationEngineOneOfSevenType =
  (typeof EvaluationEngineOneOfSevenType)[keyof typeof EvaluationEngineOneOfSevenType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EvaluationEngineOneOfSevenType = {
  passthrough: "passthrough",
} as const;
