/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { EvaluationEngineOneOf } from "./evaluationEngineOneOf";
import type { EvaluationEngineOneOfFour } from "./evaluationEngineOneOfFour";

/**
 * An evaluation implementation selected by an evaluator definition.
 */
export type EvaluationEngine =
  | EvaluationEngineOneOf
  | EvaluationEngineOneOfFour;
