/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { LlmDef } from "./llmDef";
import type { OpaDef } from "./opaDef";
import type { SystemOneDef } from "./systemOneDef";

/**
 * An evaluation implementation selected by an evaluator definition.
 */
export type EvaluationEngine =
  | (LlmDef & {
      type: "llm";
    })
  | (SystemOneDef & {
      type: "typesafe-system-one";
    })
  | (OpaDef & {
      type: "opa";
    })
  | {
      type: "passthrough";
    };
