/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * Runtime readiness of the active evaluator configuration.
 */
export type EvaluatorReadiness =
  (typeof EvaluatorReadiness)[keyof typeof EvaluatorReadiness];

export const EvaluatorReadiness = {
  ready: "ready",
  degraded: "degraded",
  invalid: "invalid",
  unconfigured: "unconfigured",
  disabled: "disabled",
} as const;
