/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * Credential bindings referenced by purpose (discovery / invocation).

Only the opaque, non-secret binding identifier is stored here. The
binding itself is a separate top-level resource owned by this forward.
 */
export type ForwardEntryCredentialBindings = { [key: string]: string };
