/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { ForwardEntryLabels } from "./forwardEntryLabels";
import type { ForwardEntryNamespace } from "./forwardEntryNamespace";
import type { ForwardEntryServerInfo } from "./forwardEntryServerInfo";
import type { ForwardEntryStatusMessage } from "./forwardEntryStatusMessage";

export interface ForwardEntry {
  address: string;
  available?: boolean;
  labels?: ForwardEntryLabels;
  name: string;
  namespace?: ForwardEntryNamespace;
  serverInfo?: ForwardEntryServerInfo;
  statusMessage?: ForwardEntryStatusMessage;
}
