/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { ForwardEntryLabels } from "./forwardEntryLabels";
import type { McpServerInfo } from "./mcpServerInfo";

export interface ForwardEntry {
  address: string;
  available?: boolean;
  /**
   * Credential bindings referenced by purpose (discovery / invocation).
   *
   * Only the opaque, non-secret binding identifier is stored here. The
   * binding itself is a separate top-level resource owned by this forward.
   */
  credentialBindings?: Partial<Record<"discovery" | "invocation", string>>;
  labels?: ForwardEntryLabels;
  name: string;
  /** @nullable */
  namespace?: string | null;
  serverInfo?: null | McpServerInfo;
  /** @nullable */
  statusMessage?: string | null;
}
