/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export interface GaugeSnapshot {
  /** @minimum 0 */
  evaluators_loaded: number;
  /** @minimum 0 */
  namespace_bindings: number;
  /** @minimum 0 */
  wasm_compiled: number;
}
