/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.1-SNAPSHOT
 */

export type GetApiV1ServiceCatalogInstructionsModel =
  (typeof GetApiV1ServiceCatalogInstructionsModel)[keyof typeof GetApiV1ServiceCatalogInstructionsModel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiV1ServiceCatalogInstructionsModel = {
  local: "local",
  docker: "docker",
  kubernetes: "kubernetes",
} as const;
