/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */

export type GetApiV1ResourcesListParams = {
  labelFilter?: string;
};
