/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { EvaluatorDef } from "./evaluatorDef";
import type { RevisionMetadata } from "./revisionMetadata";

export type GetEvaluatorRevision200 = {
  evaluators: EvaluatorDef[];
  revision: RevisionMetadata;
};
