/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { GovernancePosture } from "./governancePosture";
import type { GetEvaluatorStatus200RevisionId } from "./getEvaluatorStatus200RevisionId";
import type { EvaluatorReadiness } from "./evaluatorReadiness";

export type GetEvaluatorStatus200 = {
  namespace: string;
  posture: GovernancePosture;
  reason_code: string;
  /** @minimum 0 */
  revision_id?: GetEvaluatorStatus200RevisionId;
  state: EvaluatorReadiness;
};
