/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * Fixed outcome dimensions; request identifiers and namespace names are excluded.
 */
export type GovernanceOutcome =
  (typeof GovernanceOutcome)[keyof typeof GovernanceOutcome];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GovernanceOutcome = {
  enforced_allow: "enforced_allow",
  enforced_deny: "enforced_deny",
  audit_allow: "audit_allow",
  audit_deny: "audit_deny",
  audit_skipped: "audit_skipped",
  no_match_allow: "no_match_allow",
  no_match_deny: "no_match_deny",
  fail_open: "fail_open",
  fail_closed: "fail_closed",
  disabled: "disabled",
} as const;
