/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * Required when governance is intentionally disabled.
 */
export type GovernancePostureDisabledReason = string | null;
