/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { AuditLevel } from "./auditLevel";
import type { EnforcementMode } from "./enforcementMode";
import type { FailureBehavior } from "./failureBehavior";
import type { NoMatchBehavior } from "./noMatchBehavior";

/**
 * The effective governance settings for one namespace.
 */
export interface GovernancePosture {
  audit_level?: AuditLevel;
  /**
   * Required when governance is intentionally disabled.
   * @nullable
   */
  disabled_reason?: string | null;
  mode?: EnforcementMode;
  no_match?: NoMatchBehavior;
  on_failure?: FailureBehavior;
}
