/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { GovernanceOutcome } from "./governanceOutcome";

export interface GovernanceMetric {
  /** @minimum 0 */
  count: number;
  mode: string;
  outcome: GovernanceOutcome;
}
