/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { InjectionMechanismOneOf } from "./injectionMechanismOneOf";
import type { InjectionMechanismOneOfThree } from "./injectionMechanismOneOfThree";
import type { InjectionMechanismOneOfFive } from "./injectionMechanismOneOfFive";

/**
 * The supported outbound credential injection mechanisms.
 */
export type InjectionMechanism =
  | InjectionMechanismOneOf
  | InjectionMechanismOneOfThree
  | InjectionMechanismOneOfFive;
