/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { InjectionMechanismOneOfFiveType } from "./injectionMechanismOneOfFiveType";

/**
 * HTTP Basic authentication with separately resolved username and password.
 */
export type InjectionMechanismOneOfFive = {
  type: InjectionMechanismOneOfFiveType;
};
