/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export type InjectionMechanismOneOfThreeType =
  (typeof InjectionMechanismOneOfThreeType)[keyof typeof InjectionMechanismOneOfThreeType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InjectionMechanismOneOfThreeType = {
  named_header: "named_header",
} as const;
