/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * The supported outbound credential injection mechanisms.
 */
export type InjectionMechanism =
  | {
      type: "bearer";
    }
  | {
      /** The (validated) header name to inject. */
      header: string;
      type: "named_header";
    }
  | {
      type: "basic";
    };
