/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { InjectionMechanismOneOfThreeType } from "./injectionMechanismOneOfThreeType";

/**
 * A static named header carrying the resolved secret as its value.
 */
export type InjectionMechanismOneOfThree = {
  /** The (validated) header name to inject. */
  header: string;
  type: InjectionMechanismOneOfThreeType;
};
