/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { InteractionCompletionId } from "./interactionCompletionId";
import type { InteractionConversationId } from "./interactionConversationId";
import type { InteractionModel } from "./interactionModel";

export interface Interaction {
  completion_id?: InteractionCompletionId;
  conversation_id?: InteractionConversationId;
  /** @minimum 0 */
  duration_ms: number;
  /** @minimum 0 */
  epoch_ms: number;
  model?: InteractionModel;
  path: string;
  request_body: unknown;
  response_body: unknown;
  /** @minimum 0 */
  status_code: number;
}
