/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { ListEvaluatorRevisions200ItemActivatedAt } from "./listEvaluatorRevisions200ItemActivatedAt";
import type { ListEvaluatorRevisions200ItemActor } from "./listEvaluatorRevisions200ItemActor";
import type { ListEvaluatorRevisions200ItemFailureReason } from "./listEvaluatorRevisions200ItemFailureReason";
import type { U64 } from "./u64";
import type { RevisionOrigin } from "./revisionOrigin";
import type { ActivationStatus } from "./activationStatus";

export type ListEvaluatorRevisions200Item = {
  activated_at?: ListEvaluatorRevisions200ItemActivatedAt;
  actor?: ListEvaluatorRevisions200ItemActor;
  checksum: string;
  created_at: string;
  failure_reason?: ListEvaluatorRevisions200ItemFailureReason;
  id: U64;
  origin: RevisionOrigin;
  status: ActivationStatus;
};
