/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { AuditDecision } from "./auditDecision";

export type ListAuditEventsParams = {
  /**
   * Inclusive ISO 8601 start time
   */
  from?: string;
  /**
   * Inclusive ISO 8601 end time
   */
  to?: string;
  namespace?: string;
  actor?: string;
  operation?: string;
  target?: string;
  decision?: AuditDecision;
  reason_code?: string;
  correlation_id?: string;
  /**
   * @minimum 0
   */
  offset?: number;
  /**
   * @minimum 0
   */
  limit?: number;
};
