/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { PluginRequires } from "./pluginRequires";

export type ListPlugins200Item = {
  entrypoint: string;
  id: string;
  name: string;
  permissions?: string[];
  requires?: PluginRequires;
  styles?: string[];
  version: string;
};
