/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { ListActionPolicyRevisions200ItemActivatedAt } from "./listActionPolicyRevisions200ItemActivatedAt";
import type { ListActionPolicyRevisions200ItemActor } from "./listActionPolicyRevisions200ItemActor";
import type { ListActionPolicyRevisions200ItemFailureReason } from "./listActionPolicyRevisions200ItemFailureReason";
import type { U64 } from "./u64";
import type { RevisionOrigin } from "./revisionOrigin";
import type { ActivationStatus } from "./activationStatus";

export type ListActionPolicyRevisions200Item = {
  activated_at?: ListActionPolicyRevisions200ItemActivatedAt;
  actor?: ListActionPolicyRevisions200ItemActor;
  checksum: string;
  created_at: string;
  failure_reason?: ListActionPolicyRevisions200ItemFailureReason;
  id: U64;
  origin: RevisionOrigin;
  status: ActivationStatus;
};
