/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { LlmOperation } from "./llmOperation";

/**
 * LLM engine configuration.
 */
export interface LlmDef {
  connection: string;
  operation: LlmOperation;
  prompt: string;
  result_schema?: unknown;
}
