/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * The cognitive operation that the LLM performs.
 */
export type LlmOperation = (typeof LlmOperation)[keyof typeof LlmOperation];

export const LlmOperation = {
  classify: "classify",
  filter: "filter",
  augment: "augment",
} as const;
