/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * The type of cognitive operation the LLM performs.
 */
export type LlmOperation = (typeof LlmOperation)[keyof typeof LlmOperation];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LlmOperation = {
  classify: "classify",
  filter: "filter",
  augment: "augment",
} as const;
