/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { DurationSnapshot } from "./durationSnapshot";

export interface LlmSnapshot {
  /** @minimum 0 */
  calls_failure: number;
  /** @minimum 0 */
  calls_success: number;
  duration: DurationSnapshot;
  /** @minimum 0 */
  empty_results: number;
}
