/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { MatchKind } from "./matchKind";

/**
 * A named matcher and its literal pattern.
 */
export interface MatchExpression {
  matcher: MatchKind;
  value: string;
}
