/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export type MatchKind = (typeof MatchKind)[keyof typeof MatchKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MatchKind = {
  exact: "exact",
  glob: "glob",
  prefix: "prefix",
} as const;
