/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export interface McpServerInfo {
  capabilities?: string[];
  /** @nullable */
  description?: string | null;
  extensions?: string[];
  /** @nullable */
  instructions?: string | null;
  serverName: string;
  version: string;
  /** @nullable */
  websiteUrl?: string | null;
}
