/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { McpServerInfoDescription } from "./mcpServerInfoDescription";
import type { McpServerInfoInstructions } from "./mcpServerInfoInstructions";
import type { McpServerInfoWebsiteUrl } from "./mcpServerInfoWebsiteUrl";

export interface McpServerInfo {
  capabilities?: string[];
  description?: McpServerInfoDescription;
  extensions?: string[];
  instructions?: McpServerInfoInstructions;
  serverName: string;
  version: string;
  websiteUrl?: McpServerInfoWebsiteUrl;
}
