/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { AuditSnapshot } from "./auditSnapshot";
import type { GaugeSnapshot } from "./gaugeSnapshot";
import type { GovernanceMetric } from "./governanceMetric";
import type { MetricsSnapshotEvaluators } from "./metricsSnapshotEvaluators";
import type { MetricsSnapshotFilters } from "./metricsSnapshotFilters";
import type { PipelineSnapshot } from "./pipelineSnapshot";

export interface MetricsSnapshot {
  audit: AuditSnapshot;
  evaluator_governance: GovernanceMetric[];
  evaluators: MetricsSnapshotEvaluators;
  filters: MetricsSnapshotFilters;
  gauges: GaugeSnapshot;
  pipeline: PipelineSnapshot;
}
