/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { NamespaceEntryAudience } from "./namespaceEntryAudience";
import type { NamespaceEntryAuthRequired } from "./namespaceEntryAuthRequired";
import type { NamespaceEntryLabels } from "./namespaceEntryLabels";

export interface NamespaceEntry {
  audience?: NamespaceEntryAudience;
  authRequired?: NamespaceEntryAuthRequired;
  labels?: NamespaceEntryLabels;
  name: string;
}
