/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { NamespaceEntryLabels } from "./namespaceEntryLabels";

export interface NamespaceEntry {
  /** @nullable */
  audience?: string | null;
  /** @nullable */
  authRequired?: boolean | null;
  labels?: NamespaceEntryLabels;
  name: string;
}
