/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * Controls the result when no governance rule matches an action.
 */
export type NoMatchBehavior =
  (typeof NoMatchBehavior)[keyof typeof NoMatchBehavior];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NoMatchBehavior = {
  allow: "allow",
  deny: "deny",
} as const;
