/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * An exact, normalized upstream origin (scheme + host + port).

Normalization lower-cases the scheme and host and makes the port explicit,
so that bindings can be matched exactly and credentials are never sent to a
different origin because of address-normalization ambiguity.
 */
export type NormalizedOrigin = string;
