/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * Optional descriptions for Noul true and false outcomes.
 */
export interface NoulCriteria {
  false: unknown;
  true: unknown;
}
