/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { NoulCriteria } from "./noulCriteria";

/**
 * A TypeSafe Noul primitive.
 */
export interface NoulDef {
  criteria?: NoulCriteria | null;
  id: string;
  instructions: unknown;
}
