/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { NoulDefCriteria } from "./noulDefCriteria";

/**
 * A TypeSafe Noul primitive.
 */
export interface NoulDef {
  criteria?: NoulDefCriteria;
  id: string;
  instructions: unknown;
}
