/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * OPA engine configuration.
 */
export interface OpaDef {
  /** Name of an entry in `opa_connections`. */
  connection: string;
  /** Slash-separated OPA data path, for example `wanaku/tool_call/allow`. */
  decision_path: string;
}
