/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export interface PipelineSnapshot {
  /** @minimum 0 */
  skipped_no_interactions: number;
  /** @minimum 0 */
  skipped_no_match: number;
  /** @minimum 0 */
  skipped_no_method: number;
  /** @minimum 0 */
  skipped_no_registry: number;
  /** @minimum 0 */
  skipped_no_state: number;
  /** @minimum 0 */
  trigger_matches: number;
  /** @minimum 0 */
  trigger_misses: number;
}
