/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { ServiceRequirement } from "./serviceRequirement";
import type { PluginCatalogEntryMetadata } from "./pluginCatalogEntryMetadata";
import type { PluginRequires } from "./pluginRequires";

/**
 * Metadata for an available plugin and its installation archive.
 */
export interface PluginCatalogEntry {
  dependencies?: ServiceRequirement[];
  description?: string;
  id: string;
  license?: string;
  metadata?: PluginCatalogEntryMetadata;
  name: string;
  publisher?: string;
  requires?: PluginRequires;
  url: string;
  version: string;
}
