/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { ServiceRequirement } from "./serviceRequirement";

export interface PluginRequires {
  hostApi?: string;
  services?: ServiceRequirement[];
}
