/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */

export type GetApiV1ToolsParams = {
  name?: string;
};

/** @deprecated Use GetApiV1ToolsParams. */
export type PostApiV1ToolsParams = GetApiV1ToolsParams;
