/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { PredicateOneOfSevenOperator } from "./predicateOneOfSevenOperator";

export type PredicateOneOfSeven = {
  operator: PredicateOneOfSevenOperator;
  pointer: string;
  values: unknown[];
};
