/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * A typed comparison against a JSON Pointer.
 */
export type Predicate =
  | {
      operator: "exists";
      pointer: string;
      value: boolean;
    }
  | {
      operator: "equals";
      pointer: string;
      value: unknown;
    }
  | {
      operator: "not_equals";
      pointer: string;
      value: unknown;
    }
  | {
      operator: "one_of";
      pointer: string;
      values: unknown[];
    }
  | {
      operator: "not_one_of";
      pointer: string;
      values: unknown[];
    };
