/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export type PredicateOneOfFiveOperator =
  (typeof PredicateOneOfFiveOperator)[keyof typeof PredicateOneOfFiveOperator];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PredicateOneOfFiveOperator = {
  not_equals: "not_equals",
} as const;
