/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export type PredicateOneOfNineOperator =
  (typeof PredicateOneOfNineOperator)[keyof typeof PredicateOneOfNineOperator];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PredicateOneOfNineOperator = {
  not_one_of: "not_one_of",
} as const;
