/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export type PredicateOneOfSevenOperator =
  (typeof PredicateOneOfSevenOperator)[keyof typeof PredicateOneOfSevenOperator];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PredicateOneOfSevenOperator = {
  one_of: "one_of",
} as const;
