/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { PredicateOneOf } from "./predicateOneOf";
import type { PredicateOneOfThree } from "./predicateOneOfThree";
import type { PredicateOneOfFive } from "./predicateOneOfFive";
import type { PredicateOneOfSeven } from "./predicateOneOfSeven";
import type { PredicateOneOfNine } from "./predicateOneOfNine";

/**
 * A typed comparison against a JSON Pointer.
 */
export type Predicate =
  | PredicateOneOf
  | PredicateOneOfThree
  | PredicateOneOfFive
  | PredicateOneOfSeven
  | PredicateOneOfNine;
