/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export type PromptRole = (typeof PromptRole)[keyof typeof PromptRole];

export const PromptRole = {
  user: "user",
  assistant: "assistant",
  system: "system",
} as const;
