/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { PromptArgument } from "./promptArgument";
import type { PromptEntryConfigurationURI } from "./promptEntryConfigurationURI";
import type { PromptEntryId } from "./promptEntryId";
import type { PromptMessage } from "./promptMessage";
import type { PromptEntryNamespace } from "./promptEntryNamespace";

export interface PromptEntry {
  arguments?: PromptArgument[];
  configurationURI?: PromptEntryConfigurationURI;
  description?: string;
  id?: PromptEntryId;
  messages?: PromptMessage[];
  name: string;
  namespace?: PromptEntryNamespace;
}
