/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { PromptArgument } from "./promptArgument";
import type { PromptMessage } from "./promptMessage";

export interface PromptEntry {
  arguments?: PromptArgument[];
  description?: string;
  /**
   * Stable identity of the forward that owns this discovered prompt.
   *
   * The forward name is immutable and serves as the `forwardId`. Routing
   * resolves the current upstream address from this identifier at retrieval
   * time. The upstream address is never used as forward identity.
   * @nullable
   */
  forwardId?: string | null;
  /** @nullable */
  id?: string | null;
  messages?: PromptMessage[];
  name: string;
  /** @nullable */
  namespace?: string | null;
}
