/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export type PromptRole = (typeof PromptRole)[keyof typeof PromptRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PromptRole = {
  user: "user",
  assistant: "assistant",
  system: "system",
} as const;
