/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 */

export type DeleteApiV1ToolsRemoveParams = {
  tool?: string;
};

/** @deprecated Use DeleteApiV1ToolsRemoveParams. */
export type PutApiV1ToolsRemoveParams = DeleteApiV1ToolsRemoveParams;
