/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export interface RedactionMetadata {
  payload_captured: boolean;
  payload_truncated: boolean;
  redacted_fields: string[];
}
