/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { CandidateSelection } from "./candidateSelection";
import type { SyntheticAction } from "./syntheticAction";

export interface ReplayRequest {
  actions?: SyntheticAction[];
  allow_external_evaluators?: boolean;
  audit_event_ids?: string[];
  candidate?: CandidateSelection;
}
