/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { SimulationReport } from "./simulationReport";

export interface ReplayDetail {
  access_expansion: boolean;
  active: SimulationReport;
  candidate: SimulationReport;
  category: string;
  compatibility_impact: boolean;
  /** @minimum 0 */
  index: number;
  outside_evidence: boolean;
}
