/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { PolicyIdentity } from "./policyIdentity";
import type { ReplayDetail } from "./replayDetail";
import type { ReplayJobCounts } from "./replayJobCounts";

export interface ReplayJob {
  counts: ReplayJobCounts;
  details: ReplayDetail[];
  /** @minimum 0 */
  duration_ms: number;
  id: string;
  identity: PolicyIdentity;
  /** @nullable */
  reason_code?: string | null;
  schema_version: string;
  skipped_audit_ids: string[];
  stale: boolean;
  status: string;
}
