/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { ResourceEntryConfigurationURI } from "./resourceEntryConfigurationURI";
import type { ResourceEntryId } from "./resourceEntryId";
import type { ResourceEntryLabels } from "./resourceEntryLabels";
import type { ResourceEntryNamespace } from "./resourceEntryNamespace";
import type { ResourceEntrySecretsURI } from "./resourceEntrySecretsURI";

export interface ResourceEntry {
  configurationURI?: ResourceEntryConfigurationURI;
  description?: string;
  id?: ResourceEntryId;
  labels?: ResourceEntryLabels;
  location: string;
  mimeType?: string;
  name: string;
  namespace?: ResourceEntryNamespace;
  secretsURI?: ResourceEntrySecretsURI;
  type: string;
}
