/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { ResourceEntryLabels } from "./resourceEntryLabels";

export interface ResourceEntry {
  description?: string;
  /**
   * Whether MCP clients can list and invoke this entry. The management API
   * lists disabled entries; MCP calls do not. Forward-sourced entries are
   * disabled instead of deleted, because the next discovery restores them.
   */
  enabled?: boolean;
  /**
   * Stable identity of the forward that owns this discovered resource.
   *
   * The forward name is immutable and serves as the `forwardId`. Routing
   * resolves the current upstream address from this identifier at read time.
   * The upstream address is never used as forward identity.
   * @nullable
   */
  forwardId?: string | null;
  /** @nullable */
  id?: string | null;
  labels?: ResourceEntryLabels;
  location: string;
  mimeType?: string;
  name: string;
  /** @nullable */
  namespace?: string | null;
  type: string;
}
