/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * Stable identity of the forward that owns this discovered resource.

The forward name is immutable and serves as the `forwardId`. Routing
resolves the current upstream address from this identifier at read time.
The upstream address is never used as forward identity.
 */
export type ResourceEntryForwardId = string | null;
