/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export type RevisionOrigin =
  (typeof RevisionOrigin)[keyof typeof RevisionOrigin];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RevisionOrigin = {
  startup: "startup",
  api: "api",
} as const;
