/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { RevisionMetadataActivatedAt } from "./revisionMetadataActivatedAt";
import type { RevisionMetadataActor } from "./revisionMetadataActor";
import type { RevisionMetadataFailureReason } from "./revisionMetadataFailureReason";
import type { U64 } from "./u64";
import type { RevisionOrigin } from "./revisionOrigin";
import type { ActivationStatus } from "./activationStatus";

export interface RevisionMetadata {
  activated_at?: RevisionMetadataActivatedAt;
  actor?: RevisionMetadataActor;
  checksum: string;
  created_at: string;
  failure_reason?: RevisionMetadataFailureReason;
  id: U64;
  origin: RevisionOrigin;
  status: ActivationStatus;
}
