/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { Effect } from "./effect";
import type { Predicate } from "./predicate";
import type { RuleMetadata } from "./ruleMetadata";
import type { Selectors } from "./selectors";

/**
 * One stable, independently auditable policy rule.
 */
export interface Rule {
  /** @nullable */
  description?: string | null;
  effect: Effect;
  id: string;
  /**
   * A safe message that can be returned to an action caller.
   * @nullable
   */
  message?: string | null;
  metadata?: RuleMetadata;
  predicates?: Predicate[];
  /** @nullable */
  reason_code?: string | null;
  selectors?: Selectors;
}
