/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export interface SchemaSnapshot {
  /** @minimum 0 */
  retries_failure: number;
  /** @minimum 0 */
  retries_success: number;
  /** @minimum 0 */
  validations_fail: number;
  /** @minimum 0 */
  validations_pass: number;
}
