/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * An opaque secret reference of the form `<scheme>:<path>`.

The scheme selects the resolver (e.g. `env`). The path is resolver-specific
and is never derived from request data.
 */
export interface SecretRef {
  path: string;
  scheme: string;
}
