/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * An opaque secret reference of the form '<scheme>:<path>'.
 */
export type SecretRef = string;
