/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { SelectorsLabels } from "./selectorsLabels";
import type { SelectorsNamespace } from "./selectorsNamespace";
import type { SelectorsOperation } from "./selectorsOperation";
import type { SelectorsTargetName } from "./selectorsTargetName";
import type { SelectorsTargetType } from "./selectorsTargetType";
import type { SelectorsUri } from "./selectorsUri";

/**
 * Transport-neutral action selectors.
 */
export interface Selectors {
  labels?: SelectorsLabels;
  namespace?: SelectorsNamespace;
  /** The action operation. MCP adapters use values such as `tools/call`. */
  operation?: SelectorsOperation;
  target_name?: SelectorsTargetName;
  target_type?: SelectorsTargetType;
  uri?: SelectorsUri;
}
