/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { CandidateSelection } from "./candidateSelection";
import type { SyntheticAction } from "./syntheticAction";

export interface SimulationRequest {
  action: SyntheticAction;
  allow_external_evaluators?: boolean;
  candidate?: CandidateSelection;
}
