/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { ValidationReport } from "./validationReport";

export interface SimulationError {
  reason_code: string;
  validation?: null | ValidationReport;
}
