/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export interface StageDecision {
  decision: string;
  matched_ids: string[];
  reason_code: string;
  stage: string;
}
