/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export interface SyntheticAction {
  /** @nullable */
  evidence_id?: string | null;
  namespace?: string;
  request: unknown;
}
