/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * Selects which part of an MCP request becomes the TypeSafe state.
 */
export type SystemOneState =
  (typeof SystemOneState)[keyof typeof SystemOneState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SystemOneState = {
  arguments: "arguments",
  context: "context",
} as const;
