/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { NoulDef } from "./noulDef";
import type { SystemOneState } from "./systemOneState";

/**
 * TypeSafe System One configuration. This first engine version supports a
Noul primitive, which returns the probability that a condition is true.
 */
export interface SystemOneDef {
  connection: string;
  noul: NoulDef;
  state?: SystemOneState;
}
