/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export type TargetType = (typeof TargetType)[keyof typeof TargetType];

export const TargetType = {
  tool: "tool",
  resource: "resource",
  prompt: "prompt",
  agent: "agent",
} as const;
