/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export type TargetType = (typeof TargetType)[keyof typeof TargetType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TargetType = {
  tool: "tool",
  resource: "resource",
  prompt: "prompt",
} as const;
