/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { ToolEntryConfigurationURI } from "./toolEntryConfigurationURI";
import type { ToolEntryId } from "./toolEntryId";
import type { ToolEntryLabels } from "./toolEntryLabels";
import type { ToolEntryNamespace } from "./toolEntryNamespace";
import type { ToolEntrySecretsURI } from "./toolEntrySecretsURI";

export interface ToolEntry {
  configurationURI?: ToolEntryConfigurationURI;
  description: string;
  id?: ToolEntryId;
  inputSchema: unknown;
  labels?: ToolEntryLabels;
  name: string;
  namespace?: ToolEntryNamespace;
  secretsURI?: ToolEntrySecretsURI;
  type: string;
  uri: string;
}
