/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { ToolEntryForwardId } from "./toolEntryForwardId";
import type { ToolEntryId } from "./toolEntryId";
import type { ToolEntryLabels } from "./toolEntryLabels";
import type { ToolEntryNamespace } from "./toolEntryNamespace";

export interface ToolEntry {
  description: string;
  /** Stable identity of the forward that owns this discovered tool.

The forward name is immutable and serves as the `forwardId`. Routing
resolves the current upstream address from this identifier at invocation
time. The upstream address is never used as forward identity. */
  forwardId?: ToolEntryForwardId;
  id?: ToolEntryId;
  inputSchema: unknown;
  labels?: ToolEntryLabels;
  name: string;
  namespace?: ToolEntryNamespace;
  type: string;
  uri: string;
}
