/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { ToolEntryLabels } from "./toolEntryLabels";

export interface ToolEntry {
  description: string;
  /**
   * Stable identity of the forward that owns this discovered tool.
   *
   * The forward name is immutable and serves as the `forwardId`. Routing
   * resolves the current upstream address from this identifier at invocation
   * time. The upstream address is never used as forward identity.
   * @nullable
   */
  forwardId?: string | null;
  /** @nullable */
  id?: string | null;
  inputSchema: unknown;
  labels?: ToolEntryLabels;
  name: string;
  /** @nullable */
  namespace?: string | null;
  type: string;
  uri: string;
}
