/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

/**
 * What triggers this evaluator.
 */
export interface TriggerDef {
  method: string;
  /** @nullable */
  namespace?: string | null;
}
