/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { EvaluatorDef } from "./evaluatorDef";

export interface UpdateEvaluatorsRequest {
  evaluators?: EvaluatorDef[];
  /**
   * @minimum 0
   * @nullable
   */
  expected_revision?: number | null;
}
