/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { EvaluatorDef } from "./evaluatorDef";
import type { UpdateEvaluatorsRequestExpectedRevision } from "./updateEvaluatorsRequestExpectedRevision";

export interface UpdateEvaluatorsRequest {
  evaluators?: EvaluatorDef[];
  /** @minimum 0 */
  expected_revision?: UpdateEvaluatorsRequestExpectedRevision;
}
