/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { ActionPolicy } from "./actionPolicy";

export interface UpdateActionPolicyRequest {
  /**
   * @minimum 0
   * @nullable
   */
  expected_revision?: number | null;
  policy: ActionPolicy;
}
