/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { UpdateActionPolicyRequestExpectedRevision } from "./updateActionPolicyRequestExpectedRevision";
import type { ActionPolicy } from "./actionPolicy";

export interface UpdateActionPolicyRequest {
  /** @minimum 0 */
  expected_revision?: UpdateActionPolicyRequestExpectedRevision;
  policy: ActionPolicy;
}
