/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { Diagnostic } from "./diagnostic";
import type { PolicyIdentity } from "./policyIdentity";

export type ValidatePolicyCandidate200 = {
  diagnostics: Diagnostic[];
  identity: PolicyIdentity;
  schema_version: string;
  stale: boolean;
  valid: boolean;
};
