/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseVecPluginCatalogEntryDataItem } from "./wanakuResponseVecPluginCatalogEntryDataItem";
import type { WanakuResponseVecPluginCatalogEntryError } from "./wanakuResponseVecPluginCatalogEntryError";

export interface WanakuResponseVecPluginCatalogEntry {
  data?: WanakuResponseVecPluginCatalogEntryDataItem[];
  error?: WanakuResponseVecPluginCatalogEntryError;
}
