/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseAuditPageData } from "./wanakuResponseAuditPageData";

export interface WanakuResponseAuditPage {
  data?: WanakuResponseAuditPageData;
  /** @nullable */
  error?: string | null;
}
