/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseActionPolicyRevisionResponseData } from "./wanakuResponseActionPolicyRevisionResponseData";
import type { WanakuResponseActionPolicyRevisionResponseError } from "./wanakuResponseActionPolicyRevisionResponseError";

export interface WanakuResponseActionPolicyRevisionResponse {
  data?: WanakuResponseActionPolicyRevisionResponseData;
  error?: WanakuResponseActionPolicyRevisionResponseError;
}
