/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseVecRevisionMetadataDataItem } from "./wanakuResponseVecRevisionMetadataDataItem";
import type { WanakuResponseVecRevisionMetadataError } from "./wanakuResponseVecRevisionMetadataError";

export interface WanakuResponseVecRevisionMetadata {
  data?: WanakuResponseVecRevisionMetadataDataItem[];
  error?: WanakuResponseVecRevisionMetadataError;
}
