/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { EvaluationEngine } from "./evaluationEngine";
import type { ErrorPolicy } from "./errorPolicy";
import type { ProcessorRef } from "./processorRef";
import type { TriggerDef } from "./triggerDef";

/**
 * A single evaluator definition: trigger + evaluation engine + processor.
 */
export type WanakuResponseVecEvaluatorDefDataItem = {
  /** The engine that produces the processor input. */
  engine: EvaluationEngine;
  name: string;
  on_error?: ErrorPolicy;
  processor: ProcessorRef;
  trigger: TriggerDef;
};
