/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.4-SNAPSHOT
 */
import type { WanakuError } from "./wanakuError";
import type { CallableReference } from "./callableReference";

export interface WanakuResponseListExtendsCallableReference {
  error?: WanakuError;
  data?: CallableReference[];
}
