/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseEvaluatorRevisionResponseData } from "./wanakuResponseEvaluatorRevisionResponseData";

export interface WanakuResponseEvaluatorRevisionResponse {
  data?: WanakuResponseEvaluatorRevisionResponseData;
  /** @nullable */
  error?: string | null;
}
