/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseHashMapStringStringData } from "./wanakuResponseHashMapStringStringData";

export interface WanakuResponseHashMapStringString {
  data?: WanakuResponseHashMapStringStringData;
  /** @nullable */
  error?: string | null;
}
