/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseInstallPluginResponseData } from "./wanakuResponseInstallPluginResponseData";
import type { WanakuResponseInstallPluginResponseError } from "./wanakuResponseInstallPluginResponseError";

export interface WanakuResponseInstallPluginResponse {
  data?: WanakuResponseInstallPluginResponseData;
  error?: WanakuResponseInstallPluginResponseError;
}
