/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseReplayJobData } from "./wanakuResponseReplayJobData";

export interface WanakuResponseReplayJob {
  data?: WanakuResponseReplayJobData;
  /** @nullable */
  error?: string | null;
}
