/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseVecRevisionMetadataDataItem } from "./wanakuResponseVecRevisionMetadataDataItem";

export interface WanakuResponseVecRevisionMetadata {
  data?: WanakuResponseVecRevisionMetadataDataItem[];
  /** @nullable */
  error?: string | null;
}
