/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseSimulationErrorData } from "./wanakuResponseSimulationErrorData";

export interface WanakuResponseSimulationError {
  data?: WanakuResponseSimulationErrorData;
  /** @nullable */
  error?: string | null;
}
