/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseAuditHealthData } from "./wanakuResponseAuditHealthData";

export interface WanakuResponseAuditHealth {
  data?: WanakuResponseAuditHealthData;
  /** @nullable */
  error?: string | null;
}
