/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { GovernancePosture } from "./governancePosture";
import type { WanakuResponseEvaluatorStatusDataRevisionId } from "./wanakuResponseEvaluatorStatusDataRevisionId";
import type { EvaluatorReadiness } from "./evaluatorReadiness";

export type WanakuResponseEvaluatorStatusData = {
  namespace: string;
  posture: GovernancePosture;
  reason_code: string;
  /** @minimum 0 */
  revision_id?: WanakuResponseEvaluatorStatusDataRevisionId;
  state: EvaluatorReadiness;
};
