/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { AuditEvent } from "./auditEvent";

export type WanakuResponseAuditPageData = {
  events: AuditEvent[];
  /** @minimum 0 */
  limit: number;
  /** @minimum 0 */
  offset: number;
  /** @minimum 0 */
  total: number;
};
