/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseVecAgentViewDataItem } from "./wanakuResponseVecAgentViewDataItem";

export interface WanakuResponseVecAgentView {
  data?: WanakuResponseVecAgentViewDataItem[];
  /** @nullable */
  error?: string | null;
}
