/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseNamespaceBindingData } from "./wanakuResponseNamespaceBindingData";

export interface WanakuResponseNamespaceBinding {
  data?: WanakuResponseNamespaceBindingData;
  /** @nullable */
  error?: string | null;
}
