/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { PluginRequires } from "./pluginRequires";
import type { ServiceRequirement } from "./serviceRequirement";
import type { WanakuResponseVecPluginCatalogEntryDataItemMetadata } from "./wanakuResponseVecPluginCatalogEntryDataItemMetadata";

/**
 * Metadata for an available plugin and its installation archive.
 */
export type WanakuResponseVecPluginCatalogEntryDataItem = {
  dependencies?: ServiceRequirement[];
  description?: string;
  id: string;
  license?: string;
  metadata?: WanakuResponseVecPluginCatalogEntryDataItemMetadata;
  name: string;
  publisher?: string;
  requires?: PluginRequires;
  url: string;
  version: string;
};
