/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseEvaluatorStatusData } from "./wanakuResponseEvaluatorStatusData";

export interface WanakuResponseEvaluatorStatus {
  data?: WanakuResponseEvaluatorStatusData;
  /** @nullable */
  error?: string | null;
}
