/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseInstallPluginResponseData } from "./wanakuResponseInstallPluginResponseData";

export interface WanakuResponseInstallPluginResponse {
  data?: WanakuResponseInstallPluginResponseData;
  /** @nullable */
  error?: string | null;
}
