/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseActionPolicyRevisionResponseData } from "./wanakuResponseActionPolicyRevisionResponseData";

export interface WanakuResponseActionPolicyRevisionResponse {
  data?: WanakuResponseActionPolicyRevisionResponseData;
  /** @nullable */
  error?: string | null;
}
