/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { GovernancePosture } from "./governancePosture";
import type { PolicyIdentity } from "./policyIdentity";
import type { RedactionMetadata } from "./redactionMetadata";
import type { StageDecision } from "./stageDecision";

export type WanakuResponseSimulationReportData = {
  baseline_used: boolean;
  conditional: boolean;
  decision: string;
  /** @minimum 0 */
  duration_ms: number;
  failure_used: boolean;
  identity: PolicyIdentity;
  namespace: string;
  operation: string;
  posture: GovernancePosture;
  redaction: RedactionMetadata;
  schema_version: string;
  stages: StageDecision[];
  stale: boolean;
  /** @nullable */
  target?: string | null;
};
