/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseAuditHealthData } from "./wanakuResponseAuditHealthData";
import type { WanakuResponseAuditHealthError } from "./wanakuResponseAuditHealthError";

export interface WanakuResponseAuditHealth {
  data?: WanakuResponseAuditHealthData;
  error?: WanakuResponseAuditHealthError;
}
