/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseVecPluginManifestDataItem } from "./wanakuResponseVecPluginManifestDataItem";

export interface WanakuResponseVecPluginManifest {
  data?: WanakuResponseVecPluginManifestDataItem[];
  /** @nullable */
  error?: string | null;
}
