/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseAuditHealthDataLastError } from "./wanakuResponseAuditHealthDataLastError";

export type WanakuResponseAuditHealthData = {
  /** @minimum 0 */
  capacity: number;
  /** @minimum 0 */
  dropped_events: number;
  healthy: boolean;
  last_error?: WanakuResponseAuditHealthDataLastError;
  /** @minimum 0 */
  retained_events: number;
};
