/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseVecEvaluatorDefDataItem } from "./wanakuResponseVecEvaluatorDefDataItem";

export interface WanakuResponseVecEvaluatorDef {
  data?: WanakuResponseVecEvaluatorDefDataItem[];
  /** @nullable */
  error?: string | null;
}
