/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseAuditEventData } from "./wanakuResponseAuditEventData";
import type { WanakuResponseAuditEventError } from "./wanakuResponseAuditEventError";

export interface WanakuResponseAuditEvent {
  data?: WanakuResponseAuditEventData;
  error?: WanakuResponseAuditEventError;
}
