/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { ActivationStatus } from "./activationStatus";
import type { RevisionOrigin } from "./revisionOrigin";
import type { U64 } from "./u64";

export type WanakuResponseVecRevisionMetadataDataItem = {
  /** @nullable */
  activated_at?: string | null;
  /** @nullable */
  actor?: string | null;
  checksum: string;
  created_at: string;
  /** @nullable */
  failure_reason?: string | null;
  id: U64;
  origin: RevisionOrigin;
  status: ActivationStatus;
};
