/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { LlmDef } from "./llmDef";
import type { ErrorPolicy } from "./errorPolicy";
import type { ProcessorRef } from "./processorRef";
import type { TriggerDef } from "./triggerDef";

/**
 * A single evaluator definition: trigger + LLM operation + processor.
 */
export type WanakuResponseVecEvaluatorDefDataItem = {
  llm: LlmDef;
  name: string;
  on_error?: ErrorPolicy;
  processor: ProcessorRef;
  trigger: TriggerDef;
};
