/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseAuditEventData } from "./wanakuResponseAuditEventData";

export interface WanakuResponseAuditEvent {
  data?: WanakuResponseAuditEventData;
  /** @nullable */
  error?: string | null;
}
