/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { EvaluatorReadiness } from "./evaluatorReadiness";
import type { GovernancePosture } from "./governancePosture";

export type WanakuResponseEvaluatorStatusData = {
  namespace: string;
  posture: GovernancePosture;
  reason_code: string;
  /**
   * @minimum 0
   * @nullable
   */
  revision_id?: number | null;
  state: EvaluatorReadiness;
};
