/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */

export type WanakuResponseAuditHealthData = {
  /** @minimum 0 */
  capacity: number;
  /** @minimum 0 */
  dropped_events: number;
  healthy: boolean;
  /** @nullable */
  last_error?: string | null;
  /** @minimum 0 */
  retained_events: number;
};
