/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { WanakuResponseVecRevisionMetadataDataItemActivatedAt } from "./wanakuResponseVecRevisionMetadataDataItemActivatedAt";
import type { WanakuResponseVecRevisionMetadataDataItemActor } from "./wanakuResponseVecRevisionMetadataDataItemActor";
import type { WanakuResponseVecRevisionMetadataDataItemFailureReason } from "./wanakuResponseVecRevisionMetadataDataItemFailureReason";
import type { U64 } from "./u64";
import type { RevisionOrigin } from "./revisionOrigin";
import type { ActivationStatus } from "./activationStatus";

export type WanakuResponseVecRevisionMetadataDataItem = {
  activated_at?: WanakuResponseVecRevisionMetadataDataItemActivatedAt;
  actor?: WanakuResponseVecRevisionMetadataDataItemActor;
  checksum: string;
  created_at: string;
  failure_reason?: WanakuResponseVecRevisionMetadataDataItemFailureReason;
  id: U64;
  origin: RevisionOrigin;
  status: ActivationStatus;
};
