/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Wanaku API
 * Wanaku MCP proxy management API
 * OpenAPI spec version: 0.3.0
 */
import type { DurationSnapshot } from "./durationSnapshot";

export interface WasmSnapshot {
  duration: DurationSnapshot;
  /** @minimum 0 */
  executions: number;
  /** @minimum 0 */
  not_found: number;
}
