/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.8-SNAPSHOT
 */
import type { Instant } from "./instant";
import type { ServiceState } from "./serviceState";

export interface ActivityRecord {
  id?: string;
  lastSeen?: Instant;
  active?: boolean;
  states?: ServiceState[];
}
