/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.2-SNAPSHOT
 */
import type { Configuration } from "./configuration";

export type ConfigurationsConfigurations = { [key: string]: Configuration };
