/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.4
 */
import type { ConfigurationsConfigurations } from "./configurationsConfigurations";

export interface Configurations {
  configurations?: ConfigurationsConfigurations;
}
