/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.2-SNAPSHOT
 */

export * from "./configuration";
export * from "./configurations";
export * from "./configurationsConfigurations";
export * from "./getApiV1ManagementTargetsResourcesList200";
export * from "./getApiV1ManagementTargetsToolsList200";
export * from "./inputSchema";
export * from "./inputSchemaProperties";
export * from "./param";
export * from "./property";
export * from "./putApiV1ManagementTargetsResourcesConfigureServiceParams";
export * from "./putApiV1ManagementTargetsResourcesLinkParams";
export * from "./putApiV1ManagementTargetsResourcesUnlinkParams";
export * from "./putApiV1ManagementTargetsToolsConfigureServiceParams";
export * from "./putApiV1ManagementTargetsToolsLinkParams";
export * from "./putApiV1ManagementTargetsToolsUnlinkParams";
export * from "./putApiV1ResourcesRemoveParams";
export * from "./putApiV1ToolsRemoveParams";
export * from "./resourceReference";
export * from "./service";
export * from "./toolReference";
