/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.2-SNAPSHOT
 */
import type { InputSchemaProperties } from "./inputSchemaProperties";

export interface InputSchema {
  properties?: InputSchemaProperties;
  required?: string[];
  type?: string;
}
