/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.3
 */
import type { InputSchemaProperties } from "./inputSchemaProperties";

export interface InputSchema {
  type?: string;
  properties?: InputSchemaProperties;
  required?: string[];
}
