/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.2-SNAPSHOT
 */
import type { Property } from "./property";

export type InputSchemaProperties = { [key: string]: Property };
