/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.3-SNAPSHOT
 */
import type { Property } from "./property";

export type InputSchemaProperties = { [key: string]: Property };
