/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.8-SNAPSHOT
 */
import type { MediaTypeParameters } from "./mediaTypeParameters";

export interface MediaType {
  type?: string;
  subtype?: string;
  parameters?: MediaTypeParameters;
  hash?: number;
  wildcardType?: boolean;
  wildcardSubtype?: boolean;
}
