/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.7-SNAPSHOT
 */

export interface Namespace {
  id?: string;
  name?: string;
  path?: string;
}
