/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.6
 */
import type { OutboundSseEventType } from "./outboundSseEventType";
import type { OutboundSseEventGenericType } from "./outboundSseEventGenericType";
import type { MediaType } from "./mediaType";

export interface OutboundSseEvent {
  id?: string;
  name?: string;
  comment?: string;
  reconnectDelay?: number;
  reconnectDelaySet?: boolean;
  type?: OutboundSseEventType;
  genericType?: OutboundSseEventGenericType;
  mediaType?: MediaType;
  data?: unknown;
}
