/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.0.8-SNAPSHOT
 */

export type OutboundSseEventGenericType = { [key: string]: unknown };
