/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.5
 */

export interface Property {
  type?: string;
  description?: string;
  target?: string;
  scope?: string;
  value?: string;
}
