/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.3
 */

export type PutApiV1ManagementTargetsResourcesConfigureServiceParams = {
  option?: string;
  value?: string;
};
