/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.2-SNAPSHOT
 */

export type PutApiV1ManagementTargetsResourcesLinkParams = {
  service?: string;
  target?: string;
};
