/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.6-SNAPSHOT
 */
import type { Param } from "./param";

export interface ResourceReference {
  id?: string;
  location?: string;
  type?: string;
  name?: string;
  description?: string;
  mimeType?: string;
  params?: Param[];
  configurationURI?: string;
  secretsURI?: string;
  namespace?: string;
}
