/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.2-SNAPSHOT
 */
import type { Param } from "./param";

export interface ResourceReference {
  description?: string;
  location?: string;
  mimeType?: string;
  name?: string;
  params?: Param[];
  type?: string;
}
