/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.6-SNAPSHOT
 */
import type { EventType } from "./eventType";
import type { ServiceTarget } from "./serviceTarget";
import type { ServiceState } from "./serviceState";

export interface ServiceTargetEvent {
  eventType?: EventType;
  id?: string;
  serviceTarget?: ServiceTarget;
  serviceState?: ServiceState;
}
