/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.7
 */
import type { Instant } from "./instant";

export interface ServiceState {
  timestamp?: Instant;
  healthy?: boolean;
  reason?: string;
}
