/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.3
 */
import type { InputSchema } from "./inputSchema";

export interface ToolReference {
  name?: string;
  description?: string;
  uri?: string;
  type?: string;
  inputSchema?: InputSchema;
}
