/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.6-SNAPSHOT
 */
import type { InputSchema } from "./inputSchema";

export interface ToolReference {
  id?: string;
  name?: string;
  description?: string;
  uri?: string;
  type?: string;
  inputSchema?: InputSchema;
  configurationURI?: string;
  secretsURI?: string;
}
