/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.7
 */
import type { ToolReference } from "./toolReference";

export interface ToolPayload {
  toolReference?: ToolReference;
  configurationData?: string;
  secretsData?: string;
  payload?: ToolReference;
}
