/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.2-SNAPSHOT
 */
import type { InputSchema } from "./inputSchema";

export interface ToolReference {
  description?: string;
  inputSchema?: InputSchema;
  name?: string;
  type?: string;
  uri?: string;
}
