/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.3
 */
import type { WanakuError } from "./wanakuError";
import type { ServerInfo } from "./serverInfo";

export interface WanakuResponseServerInfo {
  error?: WanakuError;
  data?: ServerInfo;
}
