/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.6
 */
import type { WanakuError } from "./wanakuError";
import type { Namespace } from "./namespace";

export interface WanakuResponseListNamespace {
  error?: WanakuError;
  data?: Namespace[];
}
