/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.6-SNAPSHOT
 */
import type { ServiceState } from "./serviceState";

export type WanakuResponseMapStringListServiceStateData = {
  [key: string]: ServiceState[];
};
