/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.7-SNAPSHOT
 */
import type { WanakuError } from "./wanakuError";

export interface WanakuResponse {
  error?: WanakuError;
  data?: unknown;
}
