/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.0.8-SNAPSHOT
 */
import type { ActivityRecord } from "./activityRecord";

export type WanakuResponseMapStringListActivityRecordData = {
  [key: string]: ActivityRecord[];
};
