/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.5-SNAPSHOT
 */
import type { WanakuError } from "./wanakuError";
import type { WanakuResponseMapStringListStateData } from "./wanakuResponseMapStringListStateData";

export interface WanakuResponseMapStringListState {
  error?: WanakuError;
  data?: WanakuResponseMapStringListStateData;
}
