/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.4-SNAPSHOT
 */
import type { WanakuError } from "./wanakuError";
import type { ResourceReference } from "./resourceReference";

export interface WanakuResponseListResourceReference {
  error?: WanakuError;
  data?: ResourceReference[];
}
