/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.8-SNAPSHOT
 */
import type { WanakuError } from "./wanakuError";
import type { ToolReference } from "./toolReference";

export interface WanakuResponseListToolReference {
  error?: WanakuError;
  data?: ToolReference[];
}
