/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.5
 */
import type { State } from "./state";

export type WanakuResponseMapStringListStateData = { [key: string]: State[] };
