catalog.dependencies.jira-update-issue=jira-update-issue/jira-update-issue.dependencies.txt
catalog.description=Update issues in Jira
catalog.name=jira-update-issue-tool
catalog.routes.jira-update-issue=jira-update-issue/jira-update-issue.camel.yaml
catalog.rules.jira-update-issue=jira-update-issue/jira-update-issue.rules.yaml
catalog.services=jira-update-issue
catalog.versions=versions.properties
