catalog.dependencies.jira-add-comment=jira-add-comment/jira-add-comment.dependencies.txt
catalog.description=Add comments to Jira issues
catalog.name=jira-add-comment-tool
catalog.routes.jira-add-comment=jira-add-comment/jira-add-comment.camel.yaml
catalog.rules.jira-add-comment=jira-add-comment/jira-add-comment.rules.yaml
catalog.services=jira-add-comment
