catalog.dependencies.jira-add-issue=jira-add-issue/jira-add-issue.dependencies.txt
catalog.description=Create issues in Jira
catalog.name=jira-add-issue-tool
catalog.routes.jira-add-issue=jira-add-issue/jira-add-issue.camel.yaml
catalog.rules.jira-add-issue=jira-add-issue/jira-add-issue.rules.yaml
catalog.services=jira-add-issue
