catalog.dependencies.qdrant-search=qdrant-search/qdrant-search.dependencies.txt
catalog.description=Perform vectorized similarity search in Qdrant
catalog.name=camel-qdrant-search-tool
catalog.properties.qdrant-search=qdrant-search/service.properties
catalog.routes.qdrant-search=qdrant-search/qdrant-search.camel.yaml
catalog.rules.qdrant-search=qdrant-search/qdrant-search.rules.yaml
catalog.services=qdrant-search
